/**
 * Project scaffolding — produces the non-Rust files a user needs to turn a
 * raw emitter output into a `cargo build`-able project.
 *
 * The Cargo.toml dependency sets mirror the versions pinned in
 * tests/cargo-build.test.ts so what users download is exactly what Anvil's CI
 * validates against. If those test dep versions drift, update this file in
 * lockstep.
 */

import type { SolanaIR, EmitterFile } from "../ir/schema.js";

type Target = "pinocchio" | "quasar" | "native";

/** Sanitize the program name into a valid Rust crate name. */
function crateName(ir: SolanaIR): string {
  const raw = ir.name || "anvil_program";
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_") || "anvil_program";
}

function cargoToml(ir: SolanaIR, target: Target): string {
  const name = crateName(ir);
  const common = `[package]
name = "${name}"
version = "0.1.0"
edition = "2021"
description = "Generated by Anvil — Anchor → ${capitalize(target)} transpile"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[dependencies]
borsh = { version = "1.5", features = ["derive"] }`;

  if (target === "pinocchio") {
    return `${common}
pinocchio = "0.9"
pinocchio-system = "0.4"
pinocchio-token = "0.4"
pinocchio-associated-token-account = "0.4"
`;
  }
  if (target === "native") {
    return `${common}
solana-program = "2.2"
spl-token = "7"
spl-associated-token-account = "6"
`;
  }
  // quasar
  return `${common}
quasar-lang = "0.0"
quasar-spl = "0.0"
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function readme(ir: SolanaIR, target: Target): string {
  const name = crateName(ir);
  const targetLabel = capitalize(target);
  const toolchain =
    target === "pinocchio"
      ? "Pinocchio is zero-copy, zero-dependency — designed by Anza for minimal CU cost."
      : target === "quasar"
        ? "Quasar is zero-allocation — designed by Blueshift for predictable CU budgets."
        : "Native uses the raw solana_program SDK — closest to the runtime.";

  return `# ${name}

Generated by **[Anvil](https://anvilsol.xyz)** from Anchor source. Target framework: **${targetLabel}**.

> ${toolchain}

---

## Prerequisites

- **Rust** 1.75 or newer — https://rustup.rs
- **Solana CLI** 1.18+ — \`sh -c "$(curl -sSfL https://release.solana.com/stable/install)"\`
- Optional: **cargo-build-sbf** (bundled with the Solana CLI) for on-chain builds

## Build

\`\`\`bash
# Host-side verification (fast — checks the code compiles).
cargo build

# BPF build — produces target/deploy/${name}.so for deploy.
cargo build-sbf
\`\`\`

## Test

\`\`\`bash
cargo test
\`\`\`

## Deploy

\`\`\`bash
# Airdrop + deploy to devnet
solana airdrop 2
solana program deploy target/deploy/${name}.so --url devnet
\`\`\`

---

## What Anvil did

Anvil parsed your Anchor source into a typed \`SolanaIR\` and emitted ${targetLabel} Rust.
The deterministic validator then ran structural checks (PDA verification, token-constraint
coverage, account-count guards, bracket balance, Anchor-leakage detection) and either
signed off or handed the output to a single-shot AI refine pass with a strict
re-validation gate.

Files included:

- \`Cargo.toml\` — pinned to the versions Anvil's CI runs against
- \`src/\` — the emitted Rust (lib.rs, state.rs, instructions/\*, helpers.rs)
- \`.gitignore\` — standard Rust/Solana exclusions
- \`anvil-manifest.json\` — metadata about this generation (target, timestamp, program stats)

## Feedback

Found an issue with the generated code? File it at
[github.com/pratikkale26/anvil](https://github.com/pratikkale26/anvil) with the
\`anvil-manifest.json\` attached — that gives the maintainers everything needed
to reproduce.
`;
}

function gitignore(): string {
  return `/target
Cargo.lock
*.so
.anchor/
node_modules/
.DS_Store
`;
}

function manifest(ir: SolanaIR, target: Target): string {
  return JSON.stringify(
    {
      generator: "anvil",
      generatorVersion: "0.3.0",
      generatedAt: new Date().toISOString(),
      target,
      programName: ir.name,
      instructionCount: ir.instructions.length,
      accountCount: ir.accounts.length,
      feedback: "https://github.com/pratikkale26/anvil/issues",
    },
    null,
    2,
  ) + "\n";
}

/**
 * Build the non-Rust project files for a target. Callers append these to the
 * existing emitter output to produce a fully buildable project bundle.
 */
export function buildProjectScaffold(ir: SolanaIR, target: Target): EmitterFile[] {
  return [
    { path: "Cargo.toml", content: cargoToml(ir, target) },
    { path: "README.md", content: readme(ir, target) },
    { path: ".gitignore", content: gitignore() },
    { path: "anvil-manifest.json", content: manifest(ir, target) },
  ];
}
