//! Staking — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Quasar
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use quasar::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use quasar_token::instructions::Transfer as TokenTransfer;
use quasar_token::instructions::MintTo as TokenMintTo;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [95, 180, 10, 172, 84, 174, 232, 40] => initialize_pool(program_id, accounts, data),
        [206, 176, 202, 18, 200, 209, 179, 108] => stake(program_id, accounts, data),
        [4, 144, 132, 71, 116, 23, 151, 80] => claim_rewards(program_id, accounts, data),
        [90, 95, 107, 42, 205, 124, 50, 225] => unstake(program_id, accounts, data),
        [160, 15, 12, 189, 160, 0, 243, 245] => pause_pool(program_id, accounts, data),
        [52, 182, 28, 44, 146, 165, 190, 119] => resume_pool(program_id, accounts, data),
        [105, 157, 0, 185, 21, 144, 163, 159] => update_reward_rate(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn initialize_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let pool = &accounts[0];
    let reward_vault = &accounts[1];
    let stake_mint = &accounts[2];
    let reward_mint = &accounts[3];
    let admin = &accounts[4];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let reward_rate: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if data.len() < 16 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let lock_duration: i64 = i64::from_le_bytes(data[8..16].try_into().unwrap());
    if data.len() < 24 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let max_stake: u64 = u64::from_le_bytes(data[16..24].try_into().unwrap());

    if !(reward_rate > 0) {
        return Err(StakingError::InvalidRewardRate.into());
    }
    if !(lock_duration > 0) {
        return Err(StakingError::InvalidLockDuration.into());
    }
    if !(max_stake > 0) {
        return Err(StakingError::InvalidMaxStake.into());
    }
    let pool_account = pool;
    let mut pool = StakingPool::from_account_info(pool_account)?;
    pool.admin = admin.key;
    pool.stake_mint = stake_mint.key;
    pool.reward_mint = reward_mint.key;
    pool.reward_rate = reward_rate;
    pool.lock_duration = lock_duration;
    pool.max_stake = max_stake;
    pool.total_staked = 0;
    let bump = bump_seed(program_id, &[b"pool", stake_mint.key().as_ref()], pool_account.key)?;
    pool.bump = bump;
    let bump = bump_seed(program_id, &[b"reward_vault", pool.key().as_ref()], reward_vault.key)?;
    pool.reward_vault_bump = bump;
    pool.is_paused = false;
    StakingPool::save(pool_account, &pool)?;
    Ok(())

}

fn stake(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let user = &accounts[0];
    let user_stake = &accounts[1];
    let pool = &accounts[2];
    let user_stake_ata = &accounts[3];
    let stake_vault = &accounts[4];

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());

    let pool_account = pool;
    let mut pool = StakingPool::from_account_info(pool_account)?;
    if !(!pool.is_paused) {
        return Err(StakingError::PoolPaused.into());
    }
    if !(amount > 0) {
        return Err(StakingError::InvalidAmount.into());
    }
    if !(pool.total_staked.checked_add(amount).ok_or(StakingError::Overflow)? <= pool.max_stake) {
        return Err(StakingError::MaxStakeExceeded.into());
    }
    let clock = quasar::sysvar::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let user_stake_account = user_stake;
    let mut user_stake = UserStake::from_account_info(user_stake_account)?;
    user_stake.owner = user.key;
    user_stake.pool = pool_account.key;
    user_stake.amount = amount;
    user_stake.staked_at = now;
    user_stake.last_claim = now;
    let bump = bump_seed(program_id, &[b"user_stake", user.key().as_ref(), pool.key().as_ref()], user_stake_account.key)?;
    user_stake.bump = bump;
    pool.total_staked = pool.total_staked
            .checked_add(amount)
            .ok_or(StakingError::Overflow)?;
    // SPL Token transfer — user_stake_ata → stake_vault
    spl_token_transfer(user_stake_ata, stake_vault, user, amount)?;
    // Event: StakeEvent
// ⚠️ Anvil: Quasar doesn't have Anchor's emit!() — log via msg! or instruction data
quasar::msg!("event:StakeEvent");
    UserStake::save(user_stake_account, &user_stake)?;
    StakingPool::save(pool_account, &pool)?;
    Ok(())

}

fn claim_rewards(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let user = &accounts[0];
    let user_stake = &accounts[1];
    let pool = &accounts[2];
    let reward_mint = &accounts[3];
    let user_reward_ata = &accounts[4];

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let user_stake_account = user_stake;
    let mut user_stake = UserStake::from_account_info(user_stake_account)?;
    if !(user_stake.owner == user.key @ StakingError::Unauthorized) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    let pool_account = pool;
    let pool = StakingPool::from_account_info(pool_account)?;
    if !(!pool.is_paused) {
        return Err(StakingError::PoolPaused.into());
    }
    let clock = quasar::sysvar::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let elapsed = now
            .checked_sub(user_stake.last_claim)
            .ok_or(StakingError::Underflow)?;
    let rewards = (user_stake.amount as i64)
            .checked_mul(elapsed)
            .ok_or(StakingError::Overflow)?
            .checked_mul(pool.reward_rate as i64)
            .ok_or(StakingError::Overflow)?
            .checked_div(1_000_000)
            .ok_or(StakingError::Overflow)? as u64;
    if !(rewards > 0) {
        return Err(StakingError::NoRewards.into());
    }
    let pool_seeds = &[
            b"pool",
            pool.stake_mint.as_ref(),
            &[pool.bump],
        ];
    let signer_seeds = &[&pool_seeds[..]];
    // SPL Token mint_to — reward_mint → user_reward_ata
    spl_token_mint_to_signed(reward_mint, user_reward_ata, pool_account, rewards, signer_seeds)?;
    user_stake.last_claim = now;
    // Event: RewardEvent
// ⚠️ Anvil: Quasar doesn't have Anchor's emit!() — log via msg! or instruction data
quasar::msg!("event:RewardEvent");
    UserStake::save(user_stake_account, &user_stake)?;
    Ok(())

}

fn unstake(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 7 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let user = &accounts[0];
    let user_stake = &accounts[1];
    let pool = &accounts[2];
    let reward_mint = &accounts[3];
    let user_stake_ata = &accounts[4];
    let stake_vault = &accounts[5];
    let user_reward_ata = &accounts[6];

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let user_stake_account = user_stake;
    let user_stake = UserStake::from_account_info(user_stake_account)?;
    if !(user_stake.owner == user.key @ StakingError::Unauthorized) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    let pool_account = pool;
    let mut pool = StakingPool::from_account_info(pool_account)?;
    if !(!pool.is_paused) {
        return Err(StakingError::PoolPaused.into());
    }
    let clock = quasar::sysvar::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let unlock_time = user_stake.staked_at
            .checked_add(pool.lock_duration)
            .ok_or(StakingError::Overflow)?;
    if !(now >= unlock_time) {
        return Err(StakingError::StillLocked.into());
    }
    let elapsed = now
            .checked_sub(user_stake.last_claim)
            .ok_or(StakingError::Underflow)?;
    let pending_rewards = (user_stake.amount as i64)
            .checked_mul(elapsed)
            .ok_or(StakingError::Overflow)?
            .checked_mul(pool.reward_rate as i64)
            .ok_or(StakingError::Overflow)?
            .checked_div(1_000_000)
            .ok_or(StakingError::Overflow)? as u64;
    let stake_seeds = &[
            b"pool",
            pool.stake_mint.as_ref(),
            &[pool.bump],
        ];
    let signer_seeds = &[&stake_seeds[..]];
    // SPL Token transfer (PDA signed) — stake_vault → user_stake_ata
    spl_token_transfer_signed(stake_vault, user_stake_ata, pool_account, token_account_amount(user_stake)?, signer_seeds)?;
    if pending_rewards > 0 {
            spl_token_mint_to_signed(reward_mint, user_reward_ata, pool, pending_rewards, signer_seeds)?;
        }
    pool.total_staked = pool.total_staked
            .checked_sub(user_stake.amount)
            .ok_or(StakingError::Underflow)?;
    // Event: UnstakeEvent
// ⚠️ Anvil: Quasar doesn't have Anchor's emit!() — log via msg! or instruction data
quasar::msg!("event:UnstakeEvent");
    close_program_account(user_stake_account, user)?;
    StakingPool::save(pool_account, &pool)?;
    Ok(())

}

fn pause_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = StakingPool::from_account_info(pool_account)?;
    if !(pool.admin == admin.key) {
        return Err(StakingError::Unauthorized.into());
    }
    pool.is_paused = true;
    StakingPool::save(pool_account, &pool)?;
    Ok(())

}

fn resume_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = StakingPool::from_account_info(pool_account)?;
    if !(pool.admin == admin.key) {
        return Err(StakingError::Unauthorized.into());
    }
    pool.is_paused = false;
    StakingPool::save(pool_account, &pool)?;
    Ok(())

}

fn update_reward_rate(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let new_rate: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());

    let pool_account = pool;
    let mut pool = StakingPool::from_account_info(pool_account)?;
    if !(pool.admin == admin.key) {
        return Err(StakingError::Unauthorized.into());
    }
    if !(new_rate > 0) {
        return Err(StakingError::InvalidRewardRate.into());
    }
    pool.reward_rate = new_rate;
    StakingPool::save(pool_account, &pool)?;
    Ok(())

}

#[repr(C)]
pub struct StakingPool {
    pub admin: Pubkey,
    pub stake_mint: Pubkey,
    pub reward_mint: Pubkey,
    pub reward_rate: u64,
    pub lock_duration: i64,
    pub max_stake: u64,
    pub total_staked: u64,
    pub bump: u8,
    pub reward_vault_bump: u8,
    pub is_paused: bool,
}

impl StakingPool {
    pub const DISCRIMINATOR: [u8; 8] = [203, 19, 214, 220, 220, 154, 24, 102];
    pub const LEN: usize = 131;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let admin = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let stake_mint = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let reward_mint = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let reward_rate: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let lock_duration: i64 = i64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let max_stake: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let total_staked: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let reward_vault_bump: u8 = data[offset];
        offset += 1;
        let is_paused: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        offset += 1;
        Ok(Self { admin, stake_mint, reward_mint, reward_rate, lock_duration, max_stake, total_staked, bump, reward_vault_bump, is_paused })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(value.admin.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(value.stake_mint.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(value.reward_mint.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.reward_rate.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.lock_duration.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.max_stake.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.total_staked.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset] = value.reward_vault_bump as u8;
        offset += 1;
        data[offset] = if value.is_paused { 1 } else { 0 };
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }
}

#[repr(C)]
pub struct UserStake {
    pub owner: Pubkey,
    pub pool: Pubkey,
    pub amount: u64,
    pub staked_at: i64,
    pub last_claim: i64,
    pub bump: u8,
}

impl UserStake {
    pub const DISCRIMINATOR: [u8; 8] = [102, 53, 163, 107, 9, 138, 87, 153];
    pub const LEN: usize = 89;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let owner = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let pool = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let amount: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let staked_at: i64 = i64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let last_claim: i64 = i64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        Ok(Self { owner, pool, amount, staked_at, last_claim, bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(value.owner.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(value.pool.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.amount.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.staked_at.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.last_claim.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

fn spl_token_transfer(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke()
}

fn spl_token_transfer_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke_signed(signer_seeds)
}

fn spl_token_mint_to(
    mint: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    TokenMintTo {
        mint,
        to,
        authority,
        amount,
    }
    .invoke()
}

fn spl_token_mint_to_signed(
    mint: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    TokenMintTo {
        mint,
        to,
        authority,
        amount,
    }
    .invoke_signed(signer_seeds)
}

fn close_program_account(
    account: &AccountInfo,
    destination: &AccountInfo,
) -> ProgramResult {
    if account.key == destination.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    **destination.try_borrow_mut_lamports()? = destination
        .lamports()
        .checked_add(lamports)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    **account.try_borrow_mut_lamports()? = 0;
    account.try_borrow_mut_data()?.fill(0);
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum StakingError {
    /// Reward rate must be greater than zero
    InvalidRewardRate = 6000,
    /// Lock duration must be greater than zero
    InvalidLockDuration = 6001,
    /// Max stake must be greater than zero
    InvalidMaxStake = 6002,
    /// Amount must be greater than zero
    InvalidAmount = 6003,
    /// Pool is paused
    PoolPaused = 6004,
    /// Max stake exceeded
    MaxStakeExceeded = 6005,
    /// No rewards to claim
    NoRewards = 6006,
    /// Tokens are still locked
    StillLocked = 6007,
    /// Unauthorized
    Unauthorized = 6008,
    /// Arithmetic overflow
    Overflow = 6009,
    /// Arithmetic underflow
    Underflow = 6010,
}

impl From<StakingError> for ProgramError {
    fn from(error: StakingError) -> Self {
        ProgramError::Custom(error as u32)
    }
}