/**
 * Migration body codegen.
 *
 * Emits the `impl Migration<From, To>` body for Anchor v1.0's Migration
 * runtime container (PR #4060). For "safe" diffs (every change is an
 * append-at-end of a new field) the body is fully generated and lossless.
 * For unsafe diffs, the body is emitted with a TODO marker and a clear
 * comment block explaining what needs human review.
 *
 * Anchor's runtime auto-detects whether an account is in the old or new
 * format and forces .migrate() before exit. This codegen layer covers the
 * .migrate() body that developers currently hand-write.
 */
import type { Diff, Change, Field, Layout } from "./types.js";

export interface CodegenOptions {
  /** Module path users will import the layouts from. Default "crate::state". */
  importPath?: string;
  /** Target framework — affects Pubkey type, ProgramResult signature. */
  target?: "anchor" | "pinocchio" | "native";
}

export function codegenMigration(from: Layout, to: Layout, diff: Diff, opts: CodegenOptions = {}): string {
  const importPath = opts.importPath ?? "crate::state";
  const target = opts.target ?? "anchor";
  const fromVersionedName = `${from.name}V${majorVersion(from.version)}`;
  const toVersionedName = `${to.name}V${majorVersion(to.version)}`;

  const banner = [
    `// AUTO-GENERATED by 'anvil migrate codegen' — do NOT edit by hand.`,
    `// Migration: ${diff.from} → ${diff.to}`,
    `// Safety:    ${diff.isSafe ? "SAFE (append-at-end)" : "UNSAFE — human review required"}`,
    `// Reason:    ${diff.reason}`,
    `//`,
    `// Anchor v1.0 Migration<From, To> primitive (PR #4060) auto-detects`,
    `// account format and calls .migrate() before exit. This file is the`,
    `// migration body; the runtime + discriminator routing is upstream.`,
  ].join("\n");

  const importLine = `use ${importPath}::{${fromVersionedName}, ${toVersionedName}};`;
  const useAnchor = target === "anchor" ? `use anchor_lang::prelude::*;\n` : ``;

  const body = diff.isSafe
    ? safeMigrationBody(from, to, diff)
    : unsafeMigrationBody(from, to, diff);

  return `${banner}

${useAnchor}${importLine}

${body}
`;
}

function safeMigrationBody(from: Layout, to: Layout, diff: Diff): string {
  const fromName = `${from.name}V${majorVersion(from.version)}`;
  const toName = `${to.name}V${majorVersion(to.version)}`;
  const carriedFields = from.fields;
  const addedFields = diff.changes.flatMap((c) =>
    c.kind === "field-added" ? [c.field] : [],
  );

  const carried = carriedFields
    .map((f) => `            ${f.name}: from.${f.name}.clone(),`)
    .join("\n");
  const added = addedFields
    .map((f) => `            ${f.name}: ${defaultExpr(f)}, // NEW: ${f.type}`)
    .join("\n");

  return `impl Migration<${fromName}, ${toName}> for ${toName} {
    fn migrate(from: &${fromName}) -> Result<${toName}> {
        Ok(${toName} {
            // Carried-over fields (byte layout preserved).
${carried}
            // New fields (default-initialized — verify these defaults match your domain).
${added}
        })
    }
}`;
}

function unsafeMigrationBody(from: Layout, to: Layout, diff: Diff): string {
  const fromName = `${from.name}V${majorVersion(from.version)}`;
  const toName = `${to.name}V${majorVersion(to.version)}`;
  const todoLines = diff.changes
    .filter((c) => c.kind !== "field-added" || c.position !== "tail")
    .map((c) => `    //   - ${describeChangeForTodo(c)}`)
    .join("\n");

  return `// ⚠️ Anvil: ${diff.reason}
// TODO(manual): the following changes need human-decided semantics:
${todoLines}
//
// Below is a SKELETON ONLY — do NOT deploy without filling in the TODOs.
impl Migration<${fromName}, ${toName}> for ${toName} {
    fn migrate(from: &${fromName}) -> Result<${toName}> {
        // TODO(manual): construct ${toName} from \`from\`. Each unsafe
        // change above requires a human decision (data preservation,
        // schema interpretation, default values, error handling).
        unimplemented!("anvil migrate codegen — unsafe migration ${diff.from} → ${diff.to}");
    }
}`;
}

function defaultExpr(f: Field): string {
  switch (f.type) {
    case "u8": case "u16": case "u32": case "u64": case "u128":
    case "i8": case "i16": case "i32": case "i64": case "i128":
      return "0";
    case "bool":
      return "false";
    case "Pubkey":
      return "Pubkey::default()";
    case "f32": case "f64":
      return "0.0";
  }
  if (f.type.startsWith("[u8;")) return `[0u8; ${parseFixedArrayLen(f.type)}]`;
  // Named struct/enum — no safe default, surface for review.
  return `Default::default() /* TODO(manual): verify ${f.type}::default() is the right zero state */`;
}

function parseFixedArrayLen(s: string): number {
  const m = s.match(/^\[u8;\s*(\d+)\]$/);
  return m ? parseInt(m[1] ?? "0", 10) : 0;
}

function describeChangeForTodo(c: Change): string {
  switch (c.kind) {
    case "field-added":
      return `Field "${c.field.name}" (${c.field.type}) added at ${c.position}. Tail-adds are safe; head/middle inserts shift byte offsets — every existing account would need re-encoding.`;
    case "field-removed":
      return `Field "${c.field.name}" (${c.field.type}) removed. The data is gone after migration — confirm no consumers still expect it.`;
    case "field-renamed":
      return `Field renamed: "${c.from.name}" → "${c.to.name}". Verify this is a true rename, not separate add+remove.`;
    case "field-retyped":
      return `Field "${c.from.name}" type changed: ${c.from.type} → ${c.to.type}. Numeric coercion may lose precision; struct↔primitive needs explicit codec.`;
    case "field-resized":
      return `Field "${c.from.name}" size changed: ${c.from.size}B → ${c.to.size}B. Same type but different byte width — confirm endianness + truncation behavior.`;
  }
}

function majorVersion(v: string): number {
  const m = v.match(/^v?(\d+)/);
  return m?.[1] ? parseInt(m[1], 10) : 1;
}
