//! Marketplace — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use pinocchio_system::instructions::Transfer as SystemTransfer;
use pinocchio_token::instructions::Transfer as TokenTransfer;
use pinocchio_token::instructions::CloseAccount as TokenCloseAccount;

mod state;

mod instructions;

mod errors;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [54, 174, 193, 67, 17, 41, 132, 38] => list(program_id, accounts, data),
        [55, 136, 205, 107, 107, 173, 4, 31] => delist(program_id, accounts, data),
        [21, 93, 113, 154, 193, 160, 242, 168] => purchase(program_id, accounts, data),
        [232, 253, 195, 247, 148, 212, 73, 222] => update_fee(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}