//! State account definitions for Marketplace

//! Generated by Anvil v0.2.0 — Target: Pinocchio


#[repr(C)]
pub struct Marketplace {
    pub admin: [u8; 32],
    pub fee_bps: u16,
    pub treasury: [u8; 32],
    pub bump: u8,
    pub listing_count: u64,
}

impl Marketplace {
    pub const DISCRIMINATOR: [u8; 8] = [70, 222, 41, 62, 78, 3, 32, 174];
    pub const LEN: usize = 75;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let admin: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let fee_bps: u16 = u16::from_le_bytes(data[offset..offset + 2].try_into().unwrap());
        offset += 2;
        let treasury: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let bump: u8 = data[offset];
        offset += 1;
        let listing_count: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        Ok(Self { admin, fee_bps, treasury, bump, listing_count })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.admin);
        offset += 32;
        data[offset..offset + 2].copy_from_slice(&value.fee_bps.to_le_bytes());
        offset += 2;
        data[offset..offset + 32].copy_from_slice(&value.treasury);
        offset += 32;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset..offset + 8].copy_from_slice(&value.listing_count.to_le_bytes());
        offset += 8;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}

#[repr(C)]
pub struct Listing {
    pub seller: [u8; 32],
    pub mint: [u8; 32],
    pub price: u64,
    pub seed: u64,
    pub bump: u8,
    pub marketplace: [u8; 32],
    pub is_active: bool,
}

impl Listing {
    pub const DISCRIMINATOR: [u8; 8] = [218, 32, 50, 73, 43, 134, 26, 58];
    pub const LEN: usize = 114;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let seller: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let mint: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let price: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let seed: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let marketplace: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let is_active: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        offset += 1;
        Ok(Self { seller, mint, price, seed, bump, marketplace, is_active })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.seller);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint);
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.price.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.seed.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset..offset + 32].copy_from_slice(&value.marketplace);
        offset += 32;
        data[offset] = if value.is_active { 1 } else { 0 };
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}