//! Staking — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Quasar
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use quasar::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use quasar_token::instructions::Transfer as TokenTransfer;
use quasar_token::instructions::MintTo as TokenMintTo;

mod state;

mod instructions;

mod errors;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [95, 180, 10, 172, 84, 174, 232, 40] => initialize_pool(program_id, accounts, data),
        [206, 176, 202, 18, 200, 209, 179, 108] => stake(program_id, accounts, data),
        [4, 144, 132, 71, 116, 23, 151, 80] => claim_rewards(program_id, accounts, data),
        [90, 95, 107, 42, 205, 124, 50, 225] => unstake(program_id, accounts, data),
        [160, 15, 12, 189, 160, 0, 243, 245] => pause_pool(program_id, accounts, data),
        [52, 182, 28, 44, 146, 165, 190, 119] => resume_pool(program_id, accounts, data),
        [105, 157, 0, 185, 21, 144, 163, 159] => update_reward_rate(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}