//! Amm — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use pinocchio_token::instructions::Transfer as TokenTransfer;
use pinocchio_token::instructions::MintTo as TokenMintTo;
use pinocchio_token::instructions::Burn as TokenBurn;

mod state;

mod instructions;

mod errors;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [95, 180, 10, 172, 84, 174, 232, 40] => initialize_pool(program_id, accounts, data),
        [181, 157, 89, 67, 143, 182, 52, 72] => add_liquidity(program_id, accounts, data),
        [80, 85, 209, 72, 24, 206, 177, 108] => remove_liquidity(program_id, accounts, data),
        [248, 198, 158, 145, 225, 117, 135, 200] => swap(program_id, accounts, data),
        [211, 216, 1, 216, 54, 191, 102, 150] => freeze_pool(program_id, accounts, data),
        [236, 22, 34, 179, 44, 68, 15, 108] => unfreeze_pool(program_id, accounts, data),
        [195, 241, 226, 216, 102, 1, 5, 122] => update_fee_rate(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}