//! State account definitions for Amm

//! Generated by Anvil v0.2.0 — Target: Pinocchio


#[repr(C)]
pub struct AmmPool {
    pub admin: [u8; 32],
    pub token_mint_a: [u8; 32],
    pub token_mint_b: [u8; 32],
    pub lp_mint: [u8; 32],
    pub fee_rate: u64,
    pub initial_price: u64,
    pub reserve_a: u64,
    pub reserve_b: u64,
    pub lp_supply: u64,
    pub total_fees_a: u64,
    pub total_fees_b: u64,
    pub bump: u8,
    pub vault_a_bump: u8,
    pub vault_b_bump: u8,
    pub is_frozen: bool,
    pub protocol_fee_rate: u64,
}

impl AmmPool {
    pub const DISCRIMINATOR: [u8; 8] = [54, 82, 185, 138, 179, 191, 211, 169];
    pub const LEN: usize = 196;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let admin: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let token_mint_a: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let token_mint_b: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let lp_mint: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let fee_rate: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let initial_price: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let reserve_a: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let reserve_b: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let lp_supply: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let total_fees_a: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let total_fees_b: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let vault_a_bump: u8 = data[offset];
        offset += 1;
        let vault_b_bump: u8 = data[offset];
        offset += 1;
        let is_frozen: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        offset += 1;
        let protocol_fee_rate: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        Ok(Self { admin, token_mint_a, token_mint_b, lp_mint, fee_rate, initial_price, reserve_a, reserve_b, lp_supply, total_fees_a, total_fees_b, bump, vault_a_bump, vault_b_bump, is_frozen, protocol_fee_rate })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.admin);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.token_mint_a);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.token_mint_b);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.lp_mint);
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.fee_rate.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.initial_price.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.reserve_a.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.reserve_b.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.lp_supply.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.total_fees_a.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.total_fees_b.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset] = value.vault_a_bump as u8;
        offset += 1;
        data[offset] = value.vault_b_bump as u8;
        offset += 1;
        data[offset] = if value.is_frozen { 1 } else { 0 };
        offset += 1;
        data[offset..offset + 8].copy_from_slice(&value.protocol_fee_rate.to_le_bytes());
        offset += 8;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}