//! Escrow — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [253, 215, 165, 116, 36, 108, 68, 80] => create_escrow(program_id, accounts, data),
        [193, 2, 224, 245, 36, 116, 65, 154] => accept_escrow(program_id, accounts, data),
        [156, 203, 54, 179, 38, 72, 33, 21] => cancel_escrow(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn create_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 6 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let maker = &accounts[0];
    let mint_a = &accounts[1];
    let mint_b = &accounts[2];
    let maker_ata_a = &accounts[3];
    let escrow = &accounts[4];
    let vault = &accounts[5];

    if !maker.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let seed: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if data.len() < 16 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let receive_amount: u64 = u64::from_le_bytes(data[8..16].try_into().unwrap());

    let mut escrow = Escrow::from_account_info(escrow)?;
    escrow.maker = *signer_key;
    escrow.mint_a = *signer_key;
    escrow.mint_b = *signer_key;
    escrow.receive_amount = receive_amount;
    escrow.seed = seed;
    let bump = bump_seed(program_id, &[b"escrow", escrow.maker.as_ref()], escrow.key())?;
    escrow.bump = bump;
    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern — verify after transformation
    anchor_spl::token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                anchor_spl::token::Transfer {
                    from: ctx.accounts.maker_ata_a.to_account_info(),
                    to: ctx.accounts.vault.to_account_info(),
                    authority: ctx.accounts.maker.to_account_info(),
                },
            ),
            ctx.accounts.maker_ata_a.amount,
        )?;

    Ok(())
}

fn accept_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let taker = &accounts[0];
    let maker = &accounts[1];
    let mint_a = &accounts[2];
    let mint_b = &accounts[3];
    let taker_ata_b = &accounts[4];
    let taker_ata_a = &accounts[5];
    let maker_ata_b = &accounts[6];
    let escrow = &accounts[7];
    let vault = &accounts[8];

    if !taker.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern — verify after transformation
    let escrow = &ctx.accounts.escrow;
    // PDA signer seeds for 'escrow'
    let escrow_data = Escrow::from_account_info(escrow)?;
    let seeds = &[
            b"escrow",
            escrow_data.maker.as_ref(),
            &escrow.seed.to_le_bytes(),
            &[escrow_data.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern — verify after transformation
    anchor_spl::token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                anchor_spl::token::Transfer {
                    from: ctx.accounts.taker_ata_b.to_account_info(),
                    to: ctx.accounts.maker_ata_b.to_account_info(),
                    authority: ctx.accounts.taker.to_account_info(),
                },
            ),
            escrow.receive_amount,
        )?;
    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern — verify after transformation
    anchor_spl::token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                anchor_spl::token::Transfer {
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.taker_ata_a.to_account_info(),
                    authority: ctx.accounts.escrow.to_account_info(),
                },
                signer_seeds,
            ),
            ctx.accounts.vault.amount,
        )?;

    Ok(())
}

fn cancel_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let maker = &accounts[0];
    let mint_a = &accounts[1];
    let maker_ata_a = &accounts[2];
    let escrow = &accounts[3];
    let vault = &accounts[4];

    if !maker.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern — verify after transformation
    let escrow = &ctx.accounts.escrow;
    // PDA signer seeds for 'escrow'
    let escrow_data = Escrow::from_account_info(escrow)?;
    let seeds = &[
            b"escrow",
            escrow_data.maker.as_ref(),
            &escrow.seed.to_le_bytes(),
            &[escrow_data.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern — verify after transformation
    anchor_spl::token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                anchor_spl::token::Transfer {
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.maker_ata_a.to_account_info(),
                    authority: ctx.accounts.escrow.to_account_info(),
                },
                signer_seeds,
            ),
            ctx.accounts.vault.amount,
        )?;

    Ok(())
}

#[repr(C)]
pub struct Escrow {
    pub maker: [u8; 32],
    pub mint_a: [u8; 32],
    pub mint_b: [u8; 32],
    pub receive_amount: u64,
    pub seed: u64,
    pub bump: u8,
}

impl Escrow {
    pub const DISCRIMINATOR: [u8; 8] = [31, 213, 123, 187, 186, 22, 218, 155];
    pub const LEN: usize = 113;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let maker: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let mint_a: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let mint_b: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let receive_amount: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let seed: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        Ok(Self { maker, mint_a, mint_b, receive_amount, seed, bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.maker);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint_a);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint_b);
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.receive_amount.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.seed.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

/// Read the amount field from an SPL Token Account (offset 64, 8 bytes LE u64)
fn token_account_amount(account: &AccountInfo) -> Result<u64, ProgramError> {
    let data = unsafe { account.borrow_data_unchecked() };
    if data.len() < 72 {
        return Err(ProgramError::InvalidAccountData);
    }
    Ok(u64::from_le_bytes(data[64..72].try_into().unwrap()))
}