//! Vault — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [242, 35, 198, 137, 82, 225, 242, 182] => deposit(program_id, accounts, data),
        [183, 18, 70, 156, 148, 109, 161, 34] => withdraw(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 3 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let authority = &accounts[2];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let vault_state_account = vault_state;
    let mut vault_state = VaultState::from_account_info(vault_state_account)?;
    vault_state.authority = *authority.key();
    vault_state.total_deposited = 0;
    let bump = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state_account.key())?;
    vault_state.bump = bump;
    let bump = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    vault_state.vault_bump = bump;
    VaultState::save(vault_state_account, &vault_state)?;
    Ok(())

}

fn deposit(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let user = &accounts[2];
    let authority = &accounts[3];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());

    if !(amount > 0) {
        return Err(VaultError::InvalidAmount.into());
    }
    let vault_state_account = vault_state;
    let mut vault_state = VaultState::from_account_info(vault_state_account)?;
    transfer_lamports(user, vault, amount)?;
    vault_state.total_deposited = vault_state.total_deposited.checked_add(amount)
            .ok_or(VaultError::Overflow)?;
    VaultState::save(vault_state_account, &vault_state)?;
    Ok(())

}

fn withdraw(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let user = &accounts[2];
    let authority = &accounts[3];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());

    if !(amount > 0) {
        return Err(VaultError::InvalidAmount.into());
    }
    let vault_state_account = vault_state;
    let vault_state = VaultState::from_account_info(vault_state_account)?;
    if !(vault.lamports() >= amount) {
        return Err(VaultError::InsufficientFunds.into());
    }
    // PDA signer seeds for 'vault'
    let seeds = &[
            b"vault",
            vault_state.authority.as_ref(),
            &[vault_state.vault_bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // System transfer with PDA signer
    transfer_lamports_signed(vault, user, amount, signer_seeds)?;
    let vault_state_account = vault_state;
    let mut vault_state = VaultState::from_account_info(vault_state_account)?;
    vault_state.total_deposited = vault_state.total_deposited.checked_sub(amount)
            .ok_or(VaultError::Underflow)?;
    VaultState::save(vault_state_account, &vault_state)?;
    Ok(())

}

#[repr(C)]
pub struct VaultState {
    pub authority: [u8; 32],
    pub total_deposited: u64,
    pub bump: u8,
    pub vault_bump: u8,
}

impl VaultState {
    pub const DISCRIMINATOR: [u8; 8] = [228, 196, 82, 165, 98, 210, 235, 152];
    pub const LEN: usize = 42;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let authority: [u8; 32] = data[offset..offset + 32].try_into().unwrap();
        offset += 32;
        let total_deposited: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let vault_bump: u8 = data[offset];
        offset += 1;
        Ok(Self { authority, total_deposited, bump, vault_bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.authority);
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.total_deposited.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset] = value.vault_bump as u8;
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

fn transfer_lamports(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    if from.key() == to.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let from_lamports = unsafe { from.borrow_mut_lamports_unchecked() };
    let to_lamports = unsafe { to.borrow_mut_lamports_unchecked() };
    *from_lamports = from_lamports
        .checked_sub(amount)
        .ok_or(ProgramError::InsufficientFunds)?;
    *to_lamports = to_lamports
        .checked_add(amount)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    Ok(())
}

fn transfer_lamports_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let ix = pinocchio::system_instruction::transfer(from.key(), to.key(), amount);
    pinocchio::program::invoke_signed(&ix, &[from.clone(), to.clone()], signer_seeds)
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum VaultError {
    /// Amount must be greater than zero
    InvalidAmount = 6000,
    /// Insufficient funds in vault
    InsufficientFunds = 6001,
    /// Arithmetic overflow
    Overflow = 6002,
    /// Arithmetic underflow
    Underflow = 6003,
}

impl From<VaultError> for ProgramError {
    fn from(error: VaultError) -> Self {
        ProgramError::Custom(error as u32)
    }
}