//! Marketplace — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Quasar
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use quasar::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use quasar_token::instructions::Transfer as TokenTransfer;
use quasar_token::instructions::CloseAccount as TokenCloseAccount;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [54, 174, 193, 67, 17, 41, 132, 38] => list(program_id, accounts, data),
        [55, 136, 205, 107, 107, 173, 4, 31] => delist(program_id, accounts, data),
        [21, 93, 113, 154, 193, 160, 242, 168] => purchase(program_id, accounts, data),
        [232, 253, 195, 247, 148, 212, 73, 222] => update_fee(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 3 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let marketplace = &accounts[0];
    let admin = &accounts[1];
    let treasury = &accounts[2];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 2 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let fee_bps: u16 = u16::from_le_bytes(data[0..2].try_into().unwrap());

    if !(fee_bps <= 10000) {
        return Err(MarketplaceError::InvalidFeeBps.into());
    }
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::from_account_info(marketplace_account)?;
    marketplace.admin = *admin.key();
    marketplace.fee_bps = fee_bps;
    marketplace.treasury = *treasury.key();
    let bump = bump_seed(program_id, &[b"marketplace"], marketplace_account.key)?;
    marketplace.bump = bump;
    marketplace.listing_count = 0;
    Marketplace::save(marketplace_account, &marketplace)?;
    Ok(())

}

fn list(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 6 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let seller = &accounts[0];
    let nft_mint = &accounts[1];
    let seller_ata = &accounts[2];
    let listing = &accounts[3];
    let marketplace = &accounts[4];
    let vault = &accounts[5];

    if !seller.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let price: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if data.len() < 16 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let seed: u64 = u64::from_le_bytes(data[8..16].try_into().unwrap());

    if !(price > 0) {
        return Err(MarketplaceError::InvalidPrice.into());
    }
    let listing_account = listing;
    let mut listing = Listing::from_account_info(listing_account)?;
    listing.seller = *seller.key();
    listing.mint = *nft_mint.key();
    listing.price = price;
    listing.seed = seed;
    let bump = bump_seed(program_id, &[b"listing", seller.key().as_ref(), &seed.to_le_bytes()], listing_account.key)?;
    listing.bump = bump;
    listing.marketplace = *marketplace.key();
    listing.is_active = true;
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::from_account_info(marketplace_account)?;
    marketplace.listing_count = marketplace.listing_count
            .checked_add(1)
            .ok_or(MarketplaceError::Overflow)?;
    // SPL Token transfer — seller_ata → vault
    spl_token_transfer(seller_ata, vault, seller, 1)?;
    Listing::save(listing_account, &listing)?;
    Marketplace::save(marketplace_account, &marketplace)?;
    Ok(())

}

fn delist(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 6 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let seller = &accounts[0];
    let nft_mint = &accounts[1];
    let seller_ata = &accounts[2];
    let listing = &accounts[3];
    let marketplace = &accounts[4];
    let vault = &accounts[5];

    if !seller.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let listing_account = listing;
    let listing = Listing::from_account_info(listing_account)?;
    if !(listing.is_active) {
        return Err(MarketplaceError::ListingNotActive.into());
    }
    if !(listing.seller == *seller.key()) {
        return Err(MarketplaceError::Unauthorized.into());
    }
    // PDA signer seeds for 'listing'
    let seed_bytes = listing.seed.to_le_bytes();
    let seeds = &[
            b"listing",
            listing.seller.as_ref(),
            &seed_bytes,
            &[listing.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → seller_ata
    spl_token_transfer_signed(vault, seller_ata, listing_account, 1, signer_seeds)?;
    // SPL Token close account — vault
    spl_token_close_account_signed(vault, seller, listing_account, signer_seeds)?;
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::from_account_info(marketplace_account)?;
    marketplace.listing_count = marketplace.listing_count
            .checked_sub(1)
            .ok_or(MarketplaceError::Underflow)?;
    close_program_account(listing_account, seller)?;
    Marketplace::save(marketplace_account, &marketplace)?;
    Ok(())

}

fn purchase(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 8 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let buyer = &accounts[0];
    let seller = &accounts[1];
    let nft_mint = &accounts[2];
    let buyer_ata = &accounts[3];
    let listing = &accounts[4];
    let marketplace = &accounts[5];
    let treasury = &accounts[6];
    let vault = &accounts[7];

    if !buyer.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let listing_account = listing;
    let listing = Listing::from_account_info(listing_account)?;
    if !(listing.is_active) {
        return Err(MarketplaceError::ListingNotActive.into());
    }
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::from_account_info(marketplace_account)?;
    // ⚠️ Anvil: Review this section — Contains possible Anchor-specific pattern
    let fee = listing.price
            .checked_mul(marketplace.fee_bps as u64)
            .ok_or(MarketplaceError::Overflow)?
            .checked_div(10000)
            .ok_or(MarketplaceError::Overflow)?;
    let seller_amount = listing.price
            .checked_sub(fee)
            .ok_or(MarketplaceError::Underflow)?;
    transfer_lamports(buyer, seller, seller_amount)?;
    transfer_lamports(buyer, treasury, fee)?;
    // PDA signer seeds for 'listing'
    let seed_bytes = listing.seed.to_le_bytes();
    let seeds = &[
            b"listing",
            listing.seller.as_ref(),
            &seed_bytes,
            &[listing.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → buyer_ata
    spl_token_transfer_signed(vault, buyer_ata, listing_account, 1, signer_seeds)?;
    // SPL Token close account — vault
    spl_token_close_account_signed(vault, seller, listing_account, signer_seeds)?;
    marketplace.listing_count = marketplace.listing_count
            .checked_sub(1)
            .ok_or(MarketplaceError::Underflow)?;
    close_program_account(listing_account, seller)?;
    Marketplace::save(marketplace_account, &marketplace)?;
    Ok(())

}

fn update_fee(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let marketplace = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 2 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let new_fee_bps: u16 = u16::from_le_bytes(data[0..2].try_into().unwrap());

    if !(new_fee_bps <= 10000) {
        return Err(MarketplaceError::InvalidFeeBps.into());
    }
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::from_account_info(marketplace_account)?;
    if !(marketplace.admin == *admin.key()) {
        return Err(MarketplaceError::Unauthorized.into());
    }
    marketplace.fee_bps = new_fee_bps;
    Marketplace::save(marketplace_account, &marketplace)?;
    Ok(())

}

#[repr(C)]
pub struct Marketplace {
    pub admin: Pubkey,
    pub fee_bps: u16,
    pub treasury: Pubkey,
    pub bump: u8,
    pub listing_count: u64,
}

impl Marketplace {
    pub const DISCRIMINATOR: [u8; 8] = [70, 222, 41, 62, 78, 3, 32, 174];
    pub const LEN: usize = 75;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let admin = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let fee_bps: u16 = u16::from_le_bytes(data[offset..offset + 2].try_into().unwrap());
        offset += 2;
        let treasury = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let bump: u8 = data[offset];
        offset += 1;
        let listing_count: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        Ok(Self { admin, fee_bps, treasury, bump, listing_count })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(value.admin.as_ref());
        offset += 32;
        data[offset..offset + 2].copy_from_slice(&value.fee_bps.to_le_bytes());
        offset += 2;
        data[offset..offset + 32].copy_from_slice(value.treasury.as_ref());
        offset += 32;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset..offset + 8].copy_from_slice(&value.listing_count.to_le_bytes());
        offset += 8;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }
}

#[repr(C)]
pub struct Listing {
    pub seller: Pubkey,
    pub mint: Pubkey,
    pub price: u64,
    pub seed: u64,
    pub bump: u8,
    pub marketplace: Pubkey,
    pub is_active: bool,
}

impl Listing {
    pub const DISCRIMINATOR: [u8; 8] = [218, 32, 50, 73, 43, 134, 26, 58];
    pub const LEN: usize = 114;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let seller = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let mint = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let price: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let seed: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let marketplace = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let is_active: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        offset += 1;
        Ok(Self { seller, mint, price, seed, bump, marketplace, is_active })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(value.seller.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(value.mint.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.price.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.seed.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset..offset + 32].copy_from_slice(value.marketplace.as_ref());
        offset += 32;
        data[offset] = if value.is_active { 1 } else { 0 };
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

fn transfer_lamports(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    if from.key == to.key {
        return Err(ProgramError::InvalidAccountData);
    }
    **from.try_borrow_mut_lamports()? = from
        .lamports()
        .checked_sub(amount)
        .ok_or(ProgramError::InsufficientFunds)?;
    **to.try_borrow_mut_lamports()? = to
        .lamports()
        .checked_add(amount)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    Ok(())
}

fn transfer_lamports_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
    _signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    if from.key == to.key {
        return Err(ProgramError::InvalidAccountData);
    }
    **from.try_borrow_mut_lamports()? = from
        .lamports()
        .checked_sub(amount)
        .ok_or(ProgramError::InsufficientFunds)?;
    **to.try_borrow_mut_lamports()? = to
        .lamports()
        .checked_add(amount)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    Ok(())
}

fn spl_token_transfer(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke()
}

fn spl_token_transfer_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke_signed(signer_seeds)
}

fn spl_token_close_account_signed(
    account: &AccountInfo,
    destination: &AccountInfo,
    authority: &AccountInfo,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    TokenCloseAccount {
        account,
        destination,
        authority,
    }
    .invoke_signed(signer_seeds)
}

fn close_program_account(
    account: &AccountInfo,
    destination: &AccountInfo,
) -> ProgramResult {
    if account.key == destination.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    **destination.try_borrow_mut_lamports()? = destination
        .lamports()
        .checked_add(lamports)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    **account.try_borrow_mut_lamports()? = 0;
    account.try_borrow_mut_data()?.fill(0);
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum MarketplaceError {
    /// Price must be greater than zero
    InvalidPrice = 6000,
    /// Fee must be between 0 and 10000 bps
    InvalidFeeBps = 6001,
    /// Listing is not active
    ListingNotActive = 6002,
    /// Unauthorized
    Unauthorized = 6003,
    /// Arithmetic overflow
    Overflow = 6004,
    /// Arithmetic underflow
    Underflow = 6005,
}

impl From<MarketplaceError> for ProgramError {
    fn from(error: MarketplaceError) -> Self {
        ProgramError::Custom(error as u32)
    }
}