//! Counter — generated by Anvil v0.1.0
//! Source framework: Anchor → Target: pinocchio
//! 
//! ⚠️  This is generated reference output. Review before deploying.
//!    Edge cases and business logic are marked with TODO.
#![deny(clippy::all)]
#![forbid(unsafe_code)]

use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use pinocchio_system::instructions::Transfer;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    // First 8 bytes = instruction discriminator
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let discriminator = &instruction_data[..8];
    let data = &instruction_data[8..];

    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
    [/* initialize discriminator: sha256("global:initialize")[..8] */0u8, 0, 0, 0, 0, 0, 0, 10] => initialize(program_id, accounts, data),
    [/* increment discriminator: sha256("global:increment")[..8] */0u8, 0, 0, 0, 0, 0, 0, 9] => increment(program_id, accounts, data),
    [/* decrement discriminator: sha256("global:decrement")[..8] */0u8, 0, 0, 0, 0, 0, 0, 9] => decrement(program_id, accounts, data),
    [/* reset discriminator: sha256("global:reset")[..8] */0u8, 0, 0, 0, 0, 0, 0, 5] => reset(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let counter = &accounts[0];
    let authority = &accounts[1];

    // Verify authority is signer
    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args: start_value: u64
    let _data_offset = 0usize;
    let _start_value: u64 = 0; // TODO: parse from data

    // TODO: implement initialize business logic

    Ok(())
}

fn increment(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let counter = &accounts[0];
    let authority = &accounts[1];

    // has_one: counter.authority
    // TODO: verify counter.authority == authority.key()
    // Verify authority is signer
    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args: amount: u64
    let _data_offset = 0usize;
    let _amount: u64 = 0; // TODO: parse from data

    // TODO: implement increment business logic

    Ok(())
}

fn decrement(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let counter = &accounts[0];
    let authority = &accounts[1];

    // has_one: counter.authority
    // TODO: verify counter.authority == authority.key()
    // Verify authority is signer
    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args: amount: u64
    let _data_offset = 0usize;
    let _amount: u64 = 0; // TODO: parse from data

    // TODO: implement decrement business logic

    Ok(())
}

fn reset(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let counter = &accounts[0];
    let authority = &accounts[1];

    // has_one: counter.authority
    // TODO: verify counter.authority == authority.key()
    // Verify authority is signer
    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // TODO: implement reset business logic

    Ok(())
}

/// Zero-copy view into CounterAccount account data (Pinocchio style)
#[repr(C)]
pub struct CounterAccount {
    pub authority: [u8; 32],
    pub count: u64,
    pub bump: u8,
}

impl CounterAccount {
    pub const LEN: usize = 41;

    /// Parse account data zero-copy — no allocations
    pub unsafe fn from_account_info(account: &AccountInfo) -> &Self {
        let data = account.borrow_data_unchecked();
        // Skip 8-byte discriminator
        &*(data.as_ptr().add(8) as *const Self)
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum CounterError {
    /// Counter overflow
    Overflow = 6000,
    /// Counter underflow
    Underflow = 6001,
}

impl From<CounterError> for ProgramError {
    fn from(e: CounterError) -> Self {
        ProgramError::Custom(e as u32)
    }
}