//! Vault — generated by Anvil v0.1.0
//! Source framework: Anchor → Target: quasar
//!
//! Supported reference paths are currently focused on the simpler demos.
#![deny(clippy::all)]

use core::convert::TryInto;
use solana_program::{
    account_info::AccountInfo,
    entrypoint,
    entrypoint::ProgramResult,
    program_error::ProgramError,
    pubkey::Pubkey,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (disc, data) = instruction_data.split_at(8);
    route(program_id, accounts, disc, data)
}

fn route(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    disc: &[u8],
    data: &[u8],
) -> ProgramResult {
    if disc == &[175, 175, 109, 31, 13, 152, 155, 237] {
        return initialize(program_id, accounts, data);
    }
    if disc == &[242, 35, 198, 137, 82, 225, 242, 182] {
        return deposit(program_id, accounts, data);
    }
    if disc == &[183, 18, 70, 156, 148, 109, 161, 34] {
        return withdraw(program_id, accounts, data);
    }
    Err(ProgramError::InvalidInstructionData)
}

fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let vault_state = accounts.get(0).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let vault = accounts.get(1).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let authority = accounts.get(2).ok_or(ProgramError::NotEnoughAccountKeys)?;

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }
    let vault_state_bump = bump_seed(program_id, &[b"vault_state", authority.key.as_ref()], vault_state.key)?;
    let vault_bump = bump_seed(program_id, &[b"vault", authority.key.as_ref()], vault.key)?;
    if vault_state.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if !vault_state.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    let vault_state_state = VaultState {
        authority: *authority.key,
        total_deposited: 0,
        bump: vault_state_bump,
        vault_bump,
    };
    VaultState::save(vault_state, &vault_state_state)?;

    Ok(())
}

fn deposit(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let vault_state = accounts.get(0).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let vault = accounts.get(1).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let user = accounts.get(2).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let authority = accounts.get(3).ok_or(ProgramError::NotEnoughAccountKeys)?;

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if amount == 0 {
        return Err(VaultError::InvalidAmount.into());
    }
    if vault_state.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if !vault_state.is_writable || !vault.is_writable || !user.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    let vault_state_bump = bump_seed(program_id, &[b"vault_state", authority.key.as_ref()], vault_state.key)?;
    let vault_bump = bump_seed(program_id, &[b"vault", authority.key.as_ref()], vault.key)?;
    let mut vault_state_state = VaultState::from_account_info(vault_state)?;
    if vault_state_state.authority != *authority.key {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault_state_state.bump != vault_state_bump || vault_state_state.vault_bump != vault_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    transfer_lamports(user, vault, amount)?;
    vault_state_state.total_deposited = vault_state_state
        .total_deposited
        .checked_add(amount)
        .ok_or(VaultError::Overflow)?;
    VaultState::save(vault_state, &vault_state_state)?;

    Ok(())
}

fn withdraw(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    let vault_state = accounts.get(0).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let vault = accounts.get(1).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let user = accounts.get(2).ok_or(ProgramError::NotEnoughAccountKeys)?;
    let authority = accounts.get(3).ok_or(ProgramError::NotEnoughAccountKeys)?;

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if amount == 0 {
        return Err(VaultError::InvalidAmount.into());
    }
    if vault_state.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if !vault_state.is_writable || !vault.is_writable || !user.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault.lamports() < amount {
        return Err(VaultError::InsufficientFunds.into());
    }
    let vault_state_bump = bump_seed(program_id, &[b"vault_state", authority.key.as_ref()], vault_state.key)?;
    let vault_bump = bump_seed(program_id, &[b"vault", authority.key.as_ref()], vault.key)?;
    let mut vault_state_state = VaultState::from_account_info(vault_state)?;
    if vault_state_state.authority != *authority.key {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault_state_state.bump != vault_state_bump || vault_state_state.vault_bump != vault_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    transfer_lamports(vault, user, amount)?;
    vault_state_state.total_deposited = vault_state_state
        .total_deposited
        .checked_sub(amount)
        .ok_or(VaultError::Underflow)?;
    VaultState::save(vault_state, &vault_state_state)?;

    Ok(())
}

#[repr(C)]
pub struct VaultState {
    pub authority: Pubkey,
    pub total_deposited: u64,
    pub bump: u8,
    pub vault_bump: u8,
}

impl VaultState {
    pub const DISCRIMINATOR: [u8; 8] = [228, 196, 82, 165, 98, 210, 235, 152];
    pub const LEN: usize = 42;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let authority: Pubkey = Pubkey::new_from_array(data[offset..offset + 32].try_into().unwrap());
        offset += 32;
        let total_deposited: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let vault_bump: u8 = data[offset];
        offset += 1;
        Ok(Self { authority, total_deposited, bump, vault_bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(value.authority.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.total_deposited.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset] = value.vault_bump as u8;
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

fn transfer_lamports(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    let mut from_lamports = from.try_borrow_mut_lamports()?;
    let mut to_lamports = to.try_borrow_mut_lamports()?;
    **from_lamports = from_lamports
        .checked_sub(amount)
        .ok_or(ProgramError::InsufficientFunds)?;
    **to_lamports = to_lamports
        .checked_add(amount)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum VaultError {
    /// Amount must be greater than zero
    InvalidAmount = 6000,
    /// Insufficient funds in vault
    InsufficientFunds = 6001,
    /// Arithmetic overflow
    Overflow = 6002,
    /// Arithmetic underflow
    Underflow = 6003,
}

impl From<VaultError> for ProgramError {
    fn from(error: VaultError) -> Self {
        ProgramError::Custom(error as u32)
    }
}