//! Vault — generated by Anvil v0.1.0
//! Source framework: Anchor → Target: pinocchio
//!
//! Supported reference paths are currently focused on the simpler demos.
#![deny(clippy::all)]

use core::convert::TryInto;
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [242, 35, 198, 137, 82, 225, 242, 182] => deposit(program_id, accounts, data),
        [183, 18, 70, 156, 148, 109, 161, 34] => withdraw(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 3 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let authority = &accounts[2];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }
    let vault_state_bump = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state.key())?;
    let vault_bump = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    if !vault_state.is_writable() || !vault.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    {
        let vault_state_data = unsafe { vault_state.borrow_mut_data_unchecked() };
        if vault_state_data.len() < VaultState::TOTAL_LEN {
            return Err(ProgramError::AccountDataTooSmall);
        }
        vault_state_data[..8].copy_from_slice(&VaultState::DISCRIMINATOR);
        // SAFETY: The account length is checked above and the account body is
        // a fixed #[repr(C)] layout written immediately after the discriminator.
        let vault_state_state = unsafe { &mut *(vault_state_data.as_mut_ptr().add(8) as *mut VaultState) };
        vault_state_state.authority = *authority.key();
        vault_state_state.total_deposited = 0;
        vault_state_state.bump = vault_state_bump;
        vault_state_state.vault_bump = vault_bump;
    }

    Ok(())
}

fn deposit(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let user = &accounts[2];
    let authority = &accounts[3];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if amount == 0 {
        return Err(VaultError::InvalidAmount.into());
    }
    if !vault_state.is_writable() || !vault.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    let vault_state_bump = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state.key())?;
    let vault_bump = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    let vault_state_state = VaultState::from_account_info_mut(vault_state)?;
    if vault_state_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault_state_state.bump != vault_state_bump || vault_state_state.vault_bump != vault_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    // TODO: invoke the system transfer CPI from user -> vault.
    vault_state_state.total_deposited = vault_state_state
        .total_deposited
        .checked_add(amount)
        .ok_or(VaultError::Overflow)?;

    Ok(())
}

fn withdraw(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let user = &accounts[2];
    let authority = &accounts[3];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if amount == 0 {
        return Err(VaultError::InvalidAmount.into());
    }
    if !vault_state.is_writable() || !vault.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault.lamports() < amount {
        return Err(VaultError::InsufficientFunds.into());
    }
    let vault_state_bump = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state.key())?;
    let vault_bump = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    let vault_state_state = VaultState::from_account_info_mut(vault_state)?;
    if vault_state_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault_state_state.bump != vault_state_bump || vault_state_state.vault_bump != vault_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    // TODO: invoke the signed system transfer CPI from vault -> user.
    vault_state_state.total_deposited = vault_state_state
        .total_deposited
        .checked_sub(amount)
        .ok_or(VaultError::Underflow)?;

    Ok(())
}

#[repr(C)]
pub struct VaultState {
    pub authority: [u8; 32],
    pub total_deposited: u64,
    pub bump: u8,
    pub vault_bump: u8,
}

impl VaultState {
    pub const DISCRIMINATOR: [u8; 8] = [228, 196, 82, 165, 98, 210, 235, 152];
    pub const LEN: usize = 42;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn from_account_info(account: &AccountInfo) -> Result<&Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // SAFETY: The discriminator and length are checked above, and the
        // generated layout uses #[repr(C)] with a fixed-size account body.
        Ok(unsafe { &*(data.as_ptr().add(8) as *const Self) })
    }

    pub fn from_account_info_mut(account: &AccountInfo) -> Result<&mut Self, ProgramError> {
        let data = unsafe { account.borrow_mut_data_unchecked() };
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // SAFETY: The discriminator and length are checked above, and the
        // generated layout uses #[repr(C)] with a fixed-size account body.
        Ok(unsafe { &mut *(data.as_mut_ptr().add(8) as *mut Self) })
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum VaultError {
    /// Amount must be greater than zero
    InvalidAmount = 6000,
    /// Insufficient funds in vault
    InsufficientFunds = 6001,
    /// Arithmetic overflow
    Overflow = 6002,
    /// Arithmetic underflow
    Underflow = 6003,
}

impl From<VaultError> for ProgramError {
    fn from(error: VaultError) -> Self {
        ProgramError::Custom(error as u32)
    }
}