//! Counter — generated by Anvil v0.1.0
//! Source framework: Anchor → Target: pinocchio
//!
//! Supported reference paths are currently focused on the simpler demos.
#![deny(clippy::all)]

use core::convert::TryInto;
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [11, 18, 104, 9, 104, 174, 59, 33] => increment(program_id, accounts, data),
        [106, 227, 168, 59, 248, 27, 150, 101] => decrement(program_id, accounts, data),
        [23, 81, 251, 84, 138, 183, 240, 214] => reset(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let start_value: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    let counter_bump = bump_seed(program_id, &[b"counter", authority.key().as_ref()], counter.key())?;
    if !counter.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    {
        let counter_data = unsafe { counter.borrow_mut_data_unchecked() };
        if counter_data.len() < CounterAccount::TOTAL_LEN {
            return Err(ProgramError::AccountDataTooSmall);
        }
        counter_data[..8].copy_from_slice(&CounterAccount::DISCRIMINATOR);
        // SAFETY: The account length is checked above and the account body is
        // a fixed #[repr(C)] layout written immediately after the discriminator.
        let counter_state = unsafe { &mut *(counter_data.as_mut_ptr().add(8) as *mut CounterAccount) };
        counter_state.authority = *authority.key();
        counter_state.count = start_value;
        counter_state.bump = counter_bump;
    }

    Ok(())
}

fn increment(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if !counter.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    let counter_bump = bump_seed(program_id, &[b"counter", authority.key().as_ref()], counter.key())?;
    let counter_state = CounterAccount::from_account_info_mut(counter)?;
    if counter_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if counter_state.bump != counter_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    counter_state.count = counter_state
        .count
        .checked_add(amount)
        .ok_or(CounterError::Overflow)?;

    Ok(())
}

fn decrement(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let amount: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if !counter.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    let counter_bump = bump_seed(program_id, &[b"counter", authority.key().as_ref()], counter.key())?;
    let counter_state = CounterAccount::from_account_info_mut(counter)?;
    if counter_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if counter_state.bump != counter_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    counter_state.count = counter_state
        .count
        .checked_sub(amount)
        .ok_or(CounterError::Underflow)?;

    Ok(())
}

fn reset(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }
    if !counter.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    let counter_bump = bump_seed(program_id, &[b"counter", authority.key().as_ref()], counter.key())?;
    let counter_state = CounterAccount::from_account_info_mut(counter)?;
    if counter_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if counter_state.bump != counter_bump {
        return Err(ProgramError::InvalidSeeds);
    }
    counter_state.count = 0;

    Ok(())
}

#[repr(C)]
pub struct CounterAccount {
    pub authority: [u8; 32],
    pub count: u64,
    pub bump: u8,
}

impl CounterAccount {
    pub const DISCRIMINATOR: [u8; 8] = [164, 8, 153, 71, 8, 44, 93, 22];
    pub const LEN: usize = 41;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn from_account_info(account: &AccountInfo) -> Result<&Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // SAFETY: The discriminator and length are checked above, and the
        // generated layout uses #[repr(C)] with a fixed-size account body.
        Ok(unsafe { &*(data.as_ptr().add(8) as *const Self) })
    }

    pub fn from_account_info_mut(account: &AccountInfo) -> Result<&mut Self, ProgramError> {
        let data = unsafe { account.borrow_mut_data_unchecked() };
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // SAFETY: The discriminator and length are checked above, and the
        // generated layout uses #[repr(C)] with a fixed-size account body.
        Ok(unsafe { &mut *(data.as_mut_ptr().add(8) as *mut Self) })
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum CounterError {
    /// Counter overflow
    Overflow = 6000,
    /// Counter underflow
    Underflow = 6001,
}

impl From<CounterError> for ProgramError {
    fn from(error: CounterError) -> Self {
        ProgramError::Custom(error as u32)
    }
}