//! Escrow — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Quasar
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use quasar::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [253, 215, 165, 116, 36, 108, 68, 80] => create_escrow(program_id, accounts, data),
        [193, 2, 224, 245, 36, 116, 65, 154] => accept_escrow(program_id, accounts, data),
        [156, 203, 54, 179, 38, 72, 33, 21] => cancel_escrow(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn create_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 6 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let maker = &accounts[0];
    let mint_a = &accounts[1];
    let mint_b = &accounts[2];
    let maker_ata_a = &accounts[3];
    let escrow = &accounts[4];
    let vault = &accounts[5];

    if !maker.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    // Args
    if data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let seed: u64 = u64::from_le_bytes(data[0..8].try_into().unwrap());
    if data.len() < 16 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let receive_amount: u64 = u64::from_le_bytes(data[8..16].try_into().unwrap());

    let escrow_account = escrow;
    let mut escrow = Escrow::from_account_info(escrow_account)?;
    escrow.maker = *maker.key();
    escrow.mint_a = *mint_a.key();
    escrow.mint_b = *mint_b.key();
    escrow.receive_amount = receive_amount;
    escrow.seed = seed;
    let bump = bump_seed(program_id, &[b"escrow", maker.key().as_ref(), seed.to_le_bytes().as_ref()], escrow_account.key)?;
    escrow.bump = bump;
    // SPL Token transfer — maker_ata_a → vault
    spl_token_transfer(maker_ata_a, vault, maker, token_account_amount(maker_ata_a)?)?;
    Escrow::save(escrow_account, &escrow)?;
    Ok(())

}

fn accept_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let taker = &accounts[0];
    let maker = &accounts[1];
    let mint_a = &accounts[2];
    let mint_b = &accounts[3];
    let taker_ata_b = &accounts[4];
    let taker_ata_a = &accounts[5];
    let maker_ata_b = &accounts[6];
    let escrow = &accounts[7];
    let vault = &accounts[8];

    if !taker.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let escrow_account = escrow;
    let escrow = Escrow::from_account_info(escrow_account)?;
    if escrow.maker != *maker.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.mint_a != *mint_a.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.mint_b != *mint_b.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    // PDA signer seeds for 'escrow'
    let seeds = &[
            b"escrow",
            escrow.maker.as_ref(),
            &escrow.seed.to_le_bytes(),
            &[escrow.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer — taker_ata_b → maker_ata_b
    spl_token_transfer(taker_ata_b, maker_ata_b, taker, escrow.receive_amount)?;
    // SPL Token transfer (PDA signed) — vault → taker_ata_a
    spl_token_transfer_signed(vault, taker_ata_a, escrow_account, token_account_amount(vault)?, signer_seeds)?;
    // SPL Token close account — vault
    spl_token_close_account_signed(vault, maker, escrow_account, signer_seeds)?;
    close_program_account(escrow_account, maker)?;
    Ok(())

}

fn cancel_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let maker = &accounts[0];
    let mint_a = &accounts[1];
    let maker_ata_a = &accounts[2];
    let escrow = &accounts[3];
    let vault = &accounts[4];

    if !maker.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let escrow_account = escrow;
    let escrow = Escrow::from_account_info(escrow_account)?;
    if escrow.maker != *maker.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.mint_a != *mint_a.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    // PDA signer seeds for 'escrow'
    let seeds = &[
            b"escrow",
            escrow.maker.as_ref(),
            &escrow.seed.to_le_bytes(),
            &[escrow.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → maker_ata_a
    spl_token_transfer_signed(vault, maker_ata_a, escrow_account, token_account_amount(vault)?, signer_seeds)?;
    // SPL Token close account — vault
    spl_token_close_account_signed(vault, maker, escrow_account, signer_seeds)?;
    close_program_account(escrow_account, maker)?;
    Ok(())

}

#[repr(C)]
pub struct Escrow {
    pub maker: Pubkey,
    pub mint_a: Pubkey,
    pub mint_b: Pubkey,
    pub receive_amount: u64,
    pub seed: u64,
    pub bump: u8,
}

impl Escrow {
    pub const DISCRIMINATOR: [u8; 8] = [31, 213, 123, 187, 186, 22, 218, 155];
    pub const LEN: usize = 121;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let maker = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let mint_a = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let mint_b = Pubkey::try_from(&data[offset..offset + 32]).unwrap();
        offset += 32;
        let receive_amount: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let seed: u64 = u64::from_le_bytes(data[offset..offset + 8].try_into().unwrap());
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        Ok(Self { maker, mint_a, mint_b, receive_amount, seed, bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(value.maker.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(value.mint_a.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(value.mint_b.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.receive_amount.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.seed.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    let (derived, bump) = Pubkey::find_program_address(seeds, program_id);
    if &derived != expected {
        return Err(ProgramError::InvalidSeeds);
    }
    Ok(bump)
}

fn spl_token_transfer(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    let ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    quasar::program::invoke(&ix, &[from.clone(), to.clone(), authority.clone()])
}

fn spl_token_transfer_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    quasar::program::invoke_signed(&ix, &[from.clone(), to.clone(), authority.clone()], signer_seeds)
}

fn close_program_account(
    account: &AccountInfo,
    destination: &AccountInfo,
) -> ProgramResult {
    if account.key == destination.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    **destination.try_borrow_mut_lamports()? = destination
        .lamports()
        .checked_add(lamports)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    **account.try_borrow_mut_lamports()? = 0;
    account.try_borrow_mut_data()?.fill(0);
    Ok(())
}