//! Amm — generated by Anvil v0.3.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]
#![allow(unexpected_cfgs, dead_code, deprecated, unused_imports)]

use core::convert::TryInto;
use borsh::{BorshDeserialize, BorshSerialize};
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use pinocchio::instruction::{Seed, Signer};
use pinocchio_system::create_account_with_minimum_balance_signed;
use pinocchio_token::instructions::Transfer as TokenTransfer;
use pinocchio_token::instructions::MintTo as TokenMintTo;
use pinocchio_token::instructions::Burn as TokenBurn;
use pinocchio::sysvars::rent::Rent;
use pinocchio::sysvars::Sysvar;

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub struct LiquidityAdded {
    pub user: [u8; 32],
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_tokens: u64,
}

impl LiquidityAdded {
    pub const DISCRIMINATOR: [u8; 8] = [154, 26, 221, 108, 238, 64, 217, 161];
}

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub struct LiquidityRemoved {
    pub user: [u8; 32],
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_tokens: u64,
}

impl LiquidityRemoved {
    pub const DISCRIMINATOR: [u8; 8] = [225, 105, 216, 39, 124, 116, 169, 189];
}

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub struct Swapped {
    pub user: [u8; 32],
    pub amount_in: u64,
    pub amount_out: u64,
    pub fee_amount: u64,
    pub a_to_b: bool,
}

impl Swapped {
    pub const DISCRIMINATOR: [u8; 8] = [217, 52, 52, 83, 147, 135, 96, 109];
}

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [95, 180, 10, 172, 84, 174, 232, 40] => initialize_pool(program_id, accounts, data),
        [181, 157, 89, 67, 143, 182, 52, 72] => add_liquidity(program_id, accounts, data),
        [80, 85, 209, 72, 24, 206, 177, 108] => remove_liquidity(program_id, accounts, data),
        [248, 198, 158, 145, 225, 117, 135, 200] => swap(program_id, accounts, data),
        [211, 216, 1, 216, 54, 191, 102, 150] => freeze_pool(program_id, accounts, data),
        [236, 22, 34, 179, 44, 68, 15, 108] => unfreeze_pool(program_id, accounts, data),
        [195, 241, 226, 216, 102, 1, 5, 122] => update_fee_rate(program_id, accounts, data),
        [11, 68, 165, 98, 18, 208, 134, 73] => withdraw_protocol_fees(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

pub fn initialize_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let vault_a = &accounts[1];
    let vault_b = &accounts[2];
    let lp_mint = &accounts[3];
    let token_mint_a = &accounts[4];
    let token_mint_b = &accounts[5];
    let admin = &accounts[6];
    let token_program = &accounts[7];
    let _system_program = &accounts[8];

    if !admin.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable() || !vault_a.is_writable() || !vault_b.is_writable() || !lp_mint.is_writable() || !admin.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let fee_rate: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let initial_price: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let bump_pool = bump_seed(program_id, &[b"pool", token_mint_a.key().as_ref(), token_mint_b.key().as_ref()], pool.key())?;
    let init_pool_seeds: &[&[u8]] = &[
            b"pool",
            token_mint_a.key().as_ref(),
            token_mint_b.key().as_ref(),
            &[bump_pool],
        ];
    let init_pool_signer_seeds = &[&init_pool_seeds[..]];
    create_program_account(pool, admin, (8 + AmmPool::INIT_SPACE) as usize, program_id, init_pool_signer_seeds)?;
    {
        let mut __init_data = unsafe { pool.borrow_mut_data_unchecked() };
        __init_data[..8].copy_from_slice(&AmmPool::DISCRIMINATOR);
    }
    let bump_vault_a = bump_seed(program_id, &[b"vault_a", pool.key().as_ref()], vault_a.key())?;
    let init_vault_a_seeds: &[&[u8]] = &[
            b"vault_a",
            pool.key().as_ref(),
            &[bump_vault_a],
        ];
    let init_vault_a_signer_seeds = &[&init_vault_a_seeds[..]];
    // Init token account: vault_a
    {
        // 1. Allocate + assign to token program (rent-exempt for 165 bytes).
        let __ta_rent = pinocchio::sysvars::rent::Rent::get()?.minimum_balance(165);
        // PDA-signed create — build a Signer<Seed> from the threaded seeds.
        let __ta_seed_group = init_vault_a_signer_seeds.first().ok_or(pinocchio::program_error::ProgramError::InvalidSeeds)?;
        let mut __ta_seeds: [pinocchio::instruction::Seed<'_>; 8] = core::array::from_fn(|_| pinocchio::instruction::Seed::from(&[][..]));
        for (i, s) in __ta_seed_group.iter().enumerate() {
            if i >= __ta_seeds.len() { return Err(pinocchio::program_error::ProgramError::InvalidSeeds); }
            __ta_seeds[i] = pinocchio::instruction::Seed::from(*s);
        }
        let __ta_signer = pinocchio::instruction::Signer::from(&__ta_seeds[..__ta_seed_group.len()]);
        pinocchio_system::instructions::CreateAccount {
            from: admin,
            to: vault_a,
            lamports: __ta_rent,
            space: 165u64,
            owner: token_program.key(),
        }.invoke_signed(&[__ta_signer])?;
        // 2. InitializeAccount3 — discriminator 18, data: 32-byte authority.
        let mut __ta_init_data = [0u8; 33];
        __ta_init_data[0] = 18;
        __ta_init_data[1..33].copy_from_slice(pool.key().as_ref());
        let __ta_init_metas = [
            pinocchio::instruction::AccountMeta::new(vault_a.key(), true, false),
            pinocchio::instruction::AccountMeta::new(token_mint_a.key(), false, false),
        ];
        let __ta_init_ix = pinocchio::instruction::Instruction {
            program_id: token_program.key(),
            accounts: &__ta_init_metas,
            data: &__ta_init_data,
        };
        pinocchio::cpi::invoke(&__ta_init_ix, &[vault_a, token_mint_a])?;
    }
    let bump_vault_b = bump_seed(program_id, &[b"vault_b", pool.key().as_ref()], vault_b.key())?;
    let init_vault_b_seeds: &[&[u8]] = &[
            b"vault_b",
            pool.key().as_ref(),
            &[bump_vault_b],
        ];
    let init_vault_b_signer_seeds = &[&init_vault_b_seeds[..]];
    // Init token account: vault_b
    {
        // 1. Allocate + assign to token program (rent-exempt for 165 bytes).
        let __ta_rent = pinocchio::sysvars::rent::Rent::get()?.minimum_balance(165);
        // PDA-signed create — build a Signer<Seed> from the threaded seeds.
        let __ta_seed_group = init_vault_b_signer_seeds.first().ok_or(pinocchio::program_error::ProgramError::InvalidSeeds)?;
        let mut __ta_seeds: [pinocchio::instruction::Seed<'_>; 8] = core::array::from_fn(|_| pinocchio::instruction::Seed::from(&[][..]));
        for (i, s) in __ta_seed_group.iter().enumerate() {
            if i >= __ta_seeds.len() { return Err(pinocchio::program_error::ProgramError::InvalidSeeds); }
            __ta_seeds[i] = pinocchio::instruction::Seed::from(*s);
        }
        let __ta_signer = pinocchio::instruction::Signer::from(&__ta_seeds[..__ta_seed_group.len()]);
        pinocchio_system::instructions::CreateAccount {
            from: admin,
            to: vault_b,
            lamports: __ta_rent,
            space: 165u64,
            owner: token_program.key(),
        }.invoke_signed(&[__ta_signer])?;
        // 2. InitializeAccount3 — discriminator 18, data: 32-byte authority.
        let mut __ta_init_data = [0u8; 33];
        __ta_init_data[0] = 18;
        __ta_init_data[1..33].copy_from_slice(pool.key().as_ref());
        let __ta_init_metas = [
            pinocchio::instruction::AccountMeta::new(vault_b.key(), true, false),
            pinocchio::instruction::AccountMeta::new(token_mint_b.key(), false, false),
        ];
        let __ta_init_ix = pinocchio::instruction::Instruction {
            program_id: token_program.key(),
            accounts: &__ta_init_metas,
            data: &__ta_init_data,
        };
        pinocchio::cpi::invoke(&__ta_init_ix, &[vault_b, token_mint_b])?;
    }
    // Init mint: lp_mint
    {
        // 1. Allocate + assign to token program (rent-exempt for 82 bytes).
        let __mint_rent = pinocchio::sysvars::rent::Rent::get()?.minimum_balance(82);
        pinocchio_system::instructions::CreateAccount {
            from: admin,
            to: lp_mint,
            lamports: __mint_rent,
            space: 82u64,
            owner: token_program.key(),
        }.invoke()?;
        // 2. InitializeMint2 — discriminator 20, decimals + authority + COption<freeze>.
        let mut __mint_init_data = [0u8; 67];
        __mint_init_data[0] = 20;
        __mint_init_data[1] = (6) as u8;
        __mint_init_data[2..34].copy_from_slice(pool.key().as_ref());
        __mint_init_data[34] = 0;
        let __mint_init_data_len: usize = 35;
        let __mint_init_metas = [
            pinocchio::instruction::AccountMeta::new(lp_mint.key(), true, false),
        ];
        let __mint_init_ix = pinocchio::instruction::Instruction {
            program_id: token_program.key(),
            accounts: &__mint_init_metas,
            data: &__mint_init_data[..__mint_init_data_len],
        };
        pinocchio::cpi::invoke(&__mint_init_ix, &[lp_mint])?;
    }
    if !(fee_rate <= 10000) {
        return Err(AmmError::InvalidFeeRate.into());
    }
    if !(initial_price > 0) {
        return Err(AmmError::InvalidPrice.into());
    }
    let pool_account = pool;
    let mut pool = AmmPool { admin: [0u8; 32], token_mint_a: [0u8; 32], token_mint_b: [0u8; 32], lp_mint: [0u8; 32], fee_rate: 0, initial_price: 0, reserve_a: 0, reserve_b: 0, lp_supply: 0, total_fees_a: 0, total_fees_b: 0, protocol_fees_a: 0, protocol_fees_b: 0, protocol_fee_rate: 0, bump: 0, vault_a_bump: 0, vault_b_bump: 0, is_frozen: false };
    pool.admin = *admin.key();
    pool.token_mint_a = *token_mint_a.key();
    pool.token_mint_b = *token_mint_b.key();
    pool.lp_mint = *lp_mint.key();
    pool.fee_rate = fee_rate;
    pool.initial_price = initial_price;
    pool.reserve_a = 0;
    pool.reserve_b = 0;
    pool.lp_supply = 0;
    pool.total_fees_a = 0;
    pool.total_fees_b = 0;
    pool.protocol_fees_a = 0;
    pool.protocol_fees_b = 0;
    pool.protocol_fee_rate = 2000;
    pool.bump = bump_pool;
    pool.vault_a_bump = bump_vault_a;
    pool.vault_b_bump = bump_vault_b;
    pool.is_frozen = false;
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn add_liquidity(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 10 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let user = &accounts[0];
    let pool = &accounts[1];
    let user_token_a = &accounts[2];
    let user_token_b = &accounts[3];
    let vault_a = &accounts[4];
    let vault_b = &accounts[5];
    let lp_mint = &accounts[6];
    let user_lp_token = &accounts[7];
    let _token_program = &accounts[8];
    let _system_program = &accounts[9];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !user.is_writable() || !pool.is_writable() || !user_token_a.is_writable() || !user_token_b.is_writable() || !vault_a.is_writable() || !vault_b.is_writable() || !lp_mint.is_writable() || !user_lp_token.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount_a_desired: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount_b_desired: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount_a_min: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount_b_min: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    let _bump_vault_a = bump_seed(program_id, &[b"vault_a", pool_account.key().as_ref()], vault_a.key())?;
    let _bump_vault_b = bump_seed(program_id, &[b"vault_b", pool_account.key().as_ref()], vault_b.key())?;
    if !(*lp_mint.key() == pool.lp_mint) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if pool.is_frozen {
        return Err(AmmError::PoolFrozen.into());
    }
    if !(amount_a_desired > 0 && amount_b_desired > 0) {
        return Err(AmmError::InvalidAmount.into());
    }
    let (amount_a, amount_b, lp_tokens) = if pool.lp_supply == 0 {
            
            let lp = (amount_a_desired as u128).checked_mul(amount_b_desired as u128).ok_or(AmmError::Overflow)?;
            let lp = integer_sqrt(lp);
            (amount_a_desired, amount_b_desired, lp as u64)
        } else {
            
            let amount_b_optimal = (amount_a_desired as u128).checked_mul(pool.reserve_b as u128).ok_or(AmmError::Overflow)?
                .checked_div(pool.reserve_a as u128).ok_or(AmmError::Overflow)? as u64;

            let (a, b) = if amount_b_optimal <= amount_b_desired {
                if !(amount_b_optimal >= amount_b_min) { return Err((AmmError::SlippageExceeded).into()); }
                (amount_a_desired, amount_b_optimal)
            } else {
                let amount_a_optimal = (amount_b_desired as u128).checked_mul(pool.reserve_a as u128).ok_or(AmmError::Overflow)?
                    .checked_div(pool.reserve_b as u128).ok_or(AmmError::Overflow)? as u64;
                if !(amount_a_optimal >= amount_a_min) { return Err((AmmError::SlippageExceeded).into()); }
                (amount_a_optimal, amount_b_desired)
            };

            let lp = std::cmp::min(
                (a as u128).checked_mul(pool.lp_supply as u128).ok_or(AmmError::Overflow)?
                    .checked_div(pool.reserve_a as u128).ok_or(AmmError::Overflow)?,
                (b as u128).checked_mul(pool.lp_supply as u128).ok_or(AmmError::Overflow)?
                    .checked_div(pool.reserve_b as u128).ok_or(AmmError::Overflow)?,
            ) as u64;

            (a, b, lp)
        };
    if !(lp_tokens > 0) {
        return Err(AmmError::InsufficientLiquidity.into());
    }
    // SPL Token transfer — user_token_a → vault_a
    spl_token_transfer(user_token_a, vault_a, user, amount_a)?;
    // SPL Token transfer — user_token_b → vault_b
    spl_token_transfer(user_token_b, vault_b, user, amount_b)?;
    let token_mint_a = pool.token_mint_a;
    let token_mint_b = pool.token_mint_b;
    let pool_bump = pool.bump;
    // PDA signer seeds for 'pool'
    let seeds: &[&[u8]] = &[
        b"pool",
        token_mint_a.as_ref(),
        token_mint_b.as_ref(),
        &[pool_bump],
    ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token mint_to — lp_mint → user_lp_token
    spl_token_mint_to_signed(lp_mint, user_lp_token, pool_account, lp_tokens, signer_seeds)?;
    pool.reserve_a = pool.reserve_a.checked_add(amount_a).ok_or(AmmError::Overflow)?;
    pool.reserve_b = pool.reserve_b.checked_add(amount_b).ok_or(AmmError::Overflow)?;
    pool.lp_supply = pool.lp_supply.checked_add(lp_tokens).ok_or(AmmError::Overflow)?;
    {
        let __evt = LiquidityAdded { user: *user.key(),
            amount_a,
            amount_b,
            lp_tokens, };
        let __evt_bytes = ::borsh::to_vec(&__evt).map_err(|_| ProgramError::InvalidAccountData)?;
        let mut __evt_payload = LiquidityAdded::DISCRIMINATOR.to_vec();
        __evt_payload.extend_from_slice(&__evt_bytes);
        pinocchio::log::sol_log_data(&[&__evt_payload]);
    }
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn remove_liquidity(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let user = &accounts[0];
    let pool = &accounts[1];
    let user_token_a = &accounts[2];
    let user_token_b = &accounts[3];
    let vault_a = &accounts[4];
    let vault_b = &accounts[5];
    let lp_mint = &accounts[6];
    let user_lp_token = &accounts[7];
    let _token_program = &accounts[8];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !user.is_writable() || !pool.is_writable() || !user_token_a.is_writable() || !user_token_b.is_writable() || !vault_a.is_writable() || !vault_b.is_writable() || !lp_mint.is_writable() || !user_lp_token.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let lp_amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let min_amount_a: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let min_amount_b: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    let _bump_vault_a = bump_seed(program_id, &[b"vault_a", pool_account.key().as_ref()], vault_a.key())?;
    let _bump_vault_b = bump_seed(program_id, &[b"vault_b", pool_account.key().as_ref()], vault_b.key())?;
    if !(*lp_mint.key() == pool.lp_mint) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if pool.is_frozen {
        return Err(AmmError::PoolFrozen.into());
    }
    if !(lp_amount > 0) {
        return Err(AmmError::InvalidAmount.into());
    }
    let amount_a = (lp_amount as u128).checked_mul(pool.reserve_a as u128).ok_or(AmmError::Overflow)?
            .checked_div(pool.lp_supply as u128).ok_or(AmmError::Overflow)? as u64;
    let amount_b = (lp_amount as u128).checked_mul(pool.reserve_b as u128).ok_or(AmmError::Overflow)?
            .checked_div(pool.lp_supply as u128).ok_or(AmmError::Overflow)? as u64;
    if !(amount_a >= min_amount_a) {
        return Err(AmmError::SlippageExceeded.into());
    }
    if !(amount_b >= min_amount_b) {
        return Err(AmmError::SlippageExceeded.into());
    }
    let token_mint_a = pool.token_mint_a;
    let token_mint_b = pool.token_mint_b;
    let pool_bump = pool.bump;
    // PDA signer seeds for 'pool'
    let seeds: &[&[u8]] = &[
        b"pool",
        token_mint_a.as_ref(),
        token_mint_b.as_ref(),
        &[pool_bump],
    ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token burn — user_lp_token
    spl_token_burn(user_lp_token, lp_mint, user, lp_amount)?;
    // SPL Token transfer (PDA signed) — vault_a → user_token_a
    spl_token_transfer_signed(vault_a, user_token_a, pool_account, amount_a, signer_seeds)?;
    // SPL Token transfer (PDA signed) — vault_b → user_token_b
    spl_token_transfer_signed(vault_b, user_token_b, pool_account, amount_b, signer_seeds)?;
    pool.reserve_a = pool.reserve_a.checked_sub(amount_a).ok_or(AmmError::Underflow)?;
    pool.reserve_b = pool.reserve_b.checked_sub(amount_b).ok_or(AmmError::Underflow)?;
    pool.lp_supply = pool.lp_supply.checked_sub(lp_amount).ok_or(AmmError::Underflow)?;
    {
        let __evt = LiquidityRemoved { user: *user.key(),
            amount_a,
            amount_b,
            lp_tokens: lp_amount, };
        let __evt_bytes = ::borsh::to_vec(&__evt).map_err(|_| ProgramError::InvalidAccountData)?;
        let mut __evt_payload = LiquidityRemoved::DISCRIMINATOR.to_vec();
        __evt_payload.extend_from_slice(&__evt_bytes);
        pinocchio::log::sol_log_data(&[&__evt_payload]);
    }
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn swap(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 7 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let user = &accounts[0];
    let pool = &accounts[1];
    let user_token_in = &accounts[2];
    let user_token_out = &accounts[3];
    let vault_a = &accounts[4];
    let vault_b = &accounts[5];
    let _token_program = &accounts[6];

    if !user.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !user.is_writable() || !pool.is_writable() || !user_token_in.is_writable() || !user_token_out.is_writable() || !vault_a.is_writable() || !vault_b.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount_in: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let minimum_amount_out: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 1 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(1);
    remaining = rest;
    let a_to_b: bool = match arg_bytes[0] {
        0 => false,
        1 => true,
        _ => return Err(ProgramError::InvalidInstructionData),
    };
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    let _bump_vault_a = bump_seed(program_id, &[b"vault_a", pool_account.key().as_ref()], vault_a.key())?;
    let _bump_vault_b = bump_seed(program_id, &[b"vault_b", pool_account.key().as_ref()], vault_b.key())?;
    if pool.is_frozen {
        return Err(AmmError::PoolFrozen.into());
    }
    if !(amount_in > 0) {
        return Err(AmmError::InvalidAmount.into());
    }
    let (reserve_in, reserve_out) = if a_to_b {
            (pool.reserve_a, pool.reserve_b)
        } else {
            (pool.reserve_b, pool.reserve_a)
        };
    if !(reserve_in > 0 && reserve_out > 0) {
        return Err(AmmError::InsufficientLiquidity.into());
    }
    let fee_amount = amount_in.checked_mul(pool.fee_rate).ok_or(AmmError::Overflow)?
            .checked_div(10000).ok_or(AmmError::Overflow)?;
    let protocol_fee = fee_amount.checked_mul(pool.protocol_fee_rate).ok_or(AmmError::Overflow)?
            .checked_div(10000).ok_or(AmmError::Overflow)?;
    let lp_fee = fee_amount.checked_sub(protocol_fee).ok_or(AmmError::Underflow)?;
    let amount_in_after_fee = amount_in.checked_sub(fee_amount).ok_or(AmmError::Underflow)?;
    let amount_out = (amount_in_after_fee as u128).checked_mul(reserve_out as u128).ok_or(AmmError::Overflow)?
            .checked_div(
                (reserve_in as u128).checked_add(amount_in_after_fee as u128).ok_or(AmmError::Overflow)?
            ).ok_or(AmmError::Overflow)? as u64;
    if !(amount_out >= minimum_amount_out) {
        return Err(AmmError::SlippageExceeded.into());
    }
    if !(amount_out < reserve_out) {
        return Err(AmmError::InsufficientLiquidity.into());
    }
    let token_mint_a = pool.token_mint_a;
    let token_mint_b = pool.token_mint_b;
    let pool_bump = pool.bump;
    // PDA signer seeds for 'pool'
    let seeds: &[&[u8]] = &[
        b"pool",
        token_mint_a.as_ref(),
        token_mint_b.as_ref(),
        &[pool_bump],
    ];
    let signer_seeds = &[&seeds[..]];
    let (vault_in, vault_out) = if a_to_b {
            (vault_a, vault_b)
        } else {
            (vault_b, vault_a)
        };
    // SPL Token transfer — user_token_in → vault_in
    spl_token_transfer(user_token_in, vault_in, user, amount_in)?;
    // SPL Token transfer (PDA signed) — vault_out → user_token_out
    spl_token_transfer_signed(vault_out, user_token_out, pool_account, amount_out, signer_seeds)?;
    if a_to_b {
            pool.reserve_a = pool.reserve_a.checked_add(amount_in_after_fee).ok_or(AmmError::Overflow)?
                .checked_add(lp_fee).ok_or(AmmError::Overflow)?;
            pool.reserve_b = pool.reserve_b.checked_sub(amount_out).ok_or(AmmError::Underflow)?;
            pool.total_fees_a = pool.total_fees_a.checked_add(lp_fee).ok_or(AmmError::Overflow)?;
            
            
            
            pool.protocol_fees_a = pool.protocol_fees_a.checked_add(protocol_fee).ok_or(AmmError::Overflow)?;
        } else {
            pool.reserve_b = pool.reserve_b.checked_add(amount_in_after_fee).ok_or(AmmError::Overflow)?
                .checked_add(lp_fee).ok_or(AmmError::Overflow)?;
            pool.reserve_a = pool.reserve_a.checked_sub(amount_out).ok_or(AmmError::Underflow)?;
            pool.total_fees_b = pool.total_fees_b.checked_add(lp_fee).ok_or(AmmError::Overflow)?;
            pool.protocol_fees_b = pool.protocol_fees_b.checked_add(protocol_fee).ok_or(AmmError::Overflow)?;
        }
    {
        let __evt = Swapped { user: *user.key(),
            amount_in,
            amount_out,
            fee_amount,
            a_to_b, };
        let __evt_bytes = ::borsh::to_vec(&__evt).map_err(|_| ProgramError::InvalidAccountData)?;
        let mut __evt_payload = Swapped::DISCRIMINATOR.to_vec();
        __evt_payload.extend_from_slice(&__evt_bytes);
        pinocchio::log::sol_log_data(&[&__evt_payload]);
    }
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn freeze_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable() || !admin.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    if pool.admin != *admin.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    pool.is_frozen = true;
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn unfreeze_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable() || !admin.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    if pool.admin != *admin.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    pool.is_frozen = false;
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn update_fee_rate(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable() || !admin.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let new_fee_rate: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    if pool.admin != *admin.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    if !(new_fee_rate <= 10000) {
        return Err(AmmError::InvalidFeeRate.into());
    }
    pool.fee_rate = new_fee_rate;
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

pub fn withdraw_protocol_fees(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 7 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let vault_a = &accounts[1];
    let vault_b = &accounts[2];
    let admin_token_a = &accounts[3];
    let admin_token_b = &accounts[4];
    let admin = &accounts[5];
    let _token_program = &accounts[6];

    if !admin.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable() || !vault_a.is_writable() || !vault_b.is_writable() || !admin_token_a.is_writable() || !admin_token_b.is_writable() || !admin.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = AmmPool::from_account_info(pool_account)?;
    if pool.admin != *admin.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let _bump_pool = bump_seed(program_id, &[b"pool", pool.token_mint_a.as_ref(), pool.token_mint_b.as_ref()], pool_account.key())?;
    let _bump_vault_a = bump_seed(program_id, &[b"vault_a", pool_account.key().as_ref()], vault_a.key())?;
    let _bump_vault_b = bump_seed(program_id, &[b"vault_b", pool_account.key().as_ref()], vault_b.key())?;
    let amount_a = pool.protocol_fees_a;
    let amount_b = pool.protocol_fees_b;
    if !(amount_a > 0 || amount_b > 0) {
        return Err(AmmError::NoProtocolFees.into());
    }
    let token_mint_a = pool.token_mint_a;
    let token_mint_b = pool.token_mint_b;
    let pool_bump = pool.bump;
    // PDA signer seeds for 'pool'
    let seeds: &[&[u8]] = &[
        b"pool",
        token_mint_a.as_ref(),
        token_mint_b.as_ref(),
        &[pool_bump],
    ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault_a → admin_token_a
    spl_token_transfer_signed(vault_a, admin_token_a, pool_account, amount_a, signer_seeds)?;
    // SPL Token transfer (PDA signed) — vault_b → admin_token_b
    spl_token_transfer_signed(vault_b, admin_token_b, pool_account, amount_b, signer_seeds)?;
    pool.protocol_fees_a = 0;
    pool.protocol_fees_b = 0;
    AmmPool::save(pool_account, &pool)?;
    Ok(())

}

#[repr(C)]
pub struct AmmPool {
    pub admin: [u8; 32],
    pub token_mint_a: [u8; 32],
    pub token_mint_b: [u8; 32],
    pub lp_mint: [u8; 32],
    pub fee_rate: u64,
    pub initial_price: u64,
    pub reserve_a: u64,
    pub reserve_b: u64,
    pub lp_supply: u64,
    pub total_fees_a: u64,
    pub total_fees_b: u64,
    pub protocol_fees_a: u64,
    pub protocol_fees_b: u64,
    pub protocol_fee_rate: u64,
    pub bump: u8,
    pub vault_a_bump: u8,
    pub vault_b_bump: u8,
    pub is_frozen: bool,
}

impl AmmPool {
    pub const DISCRIMINATOR: [u8; 8] = [54, 82, 185, 138, 179, 191, 211, 169];
    pub const INIT_SPACE: usize = 212;
    pub const LEN: usize = 212;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // Alias to dodge field-name shadowing — a field named `data` would
        // shadow the parameter and break subsequent field reads.
        let __data_buf: &[u8] = data;
        let mut offset = 8usize;
        let admin: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let token_mint_a: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let token_mint_b: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let lp_mint: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let fee_rate: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let initial_price: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let reserve_a: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let reserve_b: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let lp_supply: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let total_fees_a: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let total_fees_b: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let protocol_fees_a: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let protocol_fees_b: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let protocol_fee_rate: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = __data_buf[offset];
        offset += 1;
        let vault_a_bump: u8 = __data_buf[offset];
        offset += 1;
        let vault_b_bump: u8 = __data_buf[offset];
        offset += 1;
        let is_frozen: bool = match __data_buf[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        Ok(Self { admin, token_mint_a, token_mint_b, lp_mint, fee_rate, initial_price, reserve_a, reserve_b, lp_supply, total_fees_a, total_fees_b, protocol_fees_a, protocol_fees_b, protocol_fee_rate, bump, vault_a_bump, vault_b_bump, is_frozen })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let __data_buf: &mut [u8] = data;
        let mut offset = 8usize;
        __data_buf[offset..offset + 32].copy_from_slice(&value.admin);
        offset += 32;
        __data_buf[offset..offset + 32].copy_from_slice(&value.token_mint_a);
        offset += 32;
        __data_buf[offset..offset + 32].copy_from_slice(&value.token_mint_b);
        offset += 32;
        __data_buf[offset..offset + 32].copy_from_slice(&value.lp_mint);
        offset += 32;
        __data_buf[offset..offset + 8].copy_from_slice(&value.fee_rate.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.initial_price.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.reserve_a.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.reserve_b.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.lp_supply.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.total_fees_a.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.total_fees_b.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.protocol_fees_a.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.protocol_fees_b.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.protocol_fee_rate.to_le_bytes());
        offset += 8;
        __data_buf[offset] = value.bump as u8;
        offset += 1;
        __data_buf[offset] = value.vault_a_bump as u8;
        offset += 1;
        __data_buf[offset] = value.vault_b_bump as u8;
        offset += 1;
        __data_buf[offset] = if value.is_frozen { 1 } else { 0 };
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}

pub fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    for bump in (0..=255u8).rev() {
        let mut seeds_with_bump: [&[u8]; 16] = [&[]; 16];
        let len = seeds.len().min(15);
        seeds_with_bump[..len].copy_from_slice(&seeds[..len]);
        let bump_slice = &[bump];
        seeds_with_bump[len] = bump_slice;
        if let Ok(derived) = pinocchio::pubkey::create_program_address(&seeds_with_bump[..len + 1], program_id) {
            if &derived == expected {
                return Ok(bump);
            }
        }
    }
    Err(ProgramError::InvalidSeeds)
}

pub fn create_program_account(
    account: &AccountInfo,
    payer: &AccountInfo,
    space: usize,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    if signer_seeds.len() > 1 {
        return Err(ProgramError::InvalidSeeds);
    }

    let signer_storage = signer_seeds.first().map(|seed_group| {
        let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
        for (index, seed) in seed_group.iter().enumerate() {
            if index >= seeds.len() {
                return Err(ProgramError::InvalidSeeds);
            }
            seeds[index] = Seed::from(*seed);
        }
        Ok((seeds, seed_group.len()))
    }).transpose()?;

    let signer_slice = if let Some((ref seeds, len)) = signer_storage {
        let signer = Signer::from(&seeds[..len]);
        create_account_with_minimum_balance_signed(account, space, program_id, payer, None, &[signer])
    } else {
        create_account_with_minimum_balance_signed(account, space, program_id, payer, None, &[])
    };

    signer_slice
}

pub fn spl_token_transfer(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke()
}

pub fn spl_token_transfer_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let seed_group = signer_seeds.first().ok_or(ProgramError::InvalidSeeds)?;
    let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
    for (i, seed) in seed_group.iter().enumerate() {
        if i >= seeds.len() { return Err(ProgramError::InvalidSeeds); }
        seeds[i] = Seed::from(*seed);
    }
    let signer = Signer::from(&seeds[..seed_group.len()]);
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke_signed(&[signer])
}

pub fn spl_token_mint_to_signed(
    mint: &AccountInfo,
    account: &AccountInfo,
    mint_authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let seed_group = signer_seeds.first().ok_or(ProgramError::InvalidSeeds)?;
    let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
    for (i, seed) in seed_group.iter().enumerate() {
        if i >= seeds.len() { return Err(ProgramError::InvalidSeeds); }
        seeds[i] = Seed::from(*seed);
    }
    let signer = Signer::from(&seeds[..seed_group.len()]);
    TokenMintTo {
        mint,
        account,
        mint_authority,
        amount,
    }
    .invoke_signed(&[signer])
}

pub fn spl_token_burn(
    account: &AccountInfo,
    mint: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    TokenBurn {
        account,
        mint,
        authority,
        amount,
    }
    .invoke()
}

// Carried from source (transformed for Pinocchio)
pub fn integer_sqrt(n: u128) -> u128 {
    if n == 0 {
        return 0;
    }
    let mut x = n;
    let mut y = (x + 1) / 2;
    while y < x {
        x = y;
        y = (x + n / x) / 2;
    }
    x
}

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║  ⚠️ Anvil TODO: helper 'transfer_to_vault' uses Anchor-only types
// ║  (InterfaceAccount, Interface<TokenInterface>, Box<Account>, etc.) that
// ║  don't exist on Pinocchio. Body commented out below; instruction call sites
// ║  are also commented out so the program compiles. MANUAL PORT REQUIRED.
// ╚════════════════════════════════════════════════════════════════════════════╝
// fn transfer_to_vault<'info>(
//     token_program: &AccountInfo<'info>,
//     from: &AccountInfo<'info>,
//     to: &AccountInfo<'info>,
//     authority: &AccountInfo<'info>,
//     amount: u64,
// ) -> Result<()> {
//     token::transfer(
//         CpiContext::new(
//             token_program.clone(),
//             Transfer { from: from.clone(), to: to.clone(), authority: authority.clone() },
//         ),
//         amount,
//     )
// }

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║  ⚠️ Anvil TODO: helper 'transfer_from_vault' uses Anchor-only types
// ║  (InterfaceAccount, Interface<TokenInterface>, Box<Account>, etc.) that
// ║  don't exist on Pinocchio. Body commented out below; instruction call sites
// ║  are also commented out so the program compiles. MANUAL PORT REQUIRED.
// ╚════════════════════════════════════════════════════════════════════════════╝
// fn transfer_from_vault<'info>(
//     token_program: &AccountInfo<'info>,
//     from: &AccountInfo<'info>,
//     to: &AccountInfo<'info>,
//     authority: &AccountInfo<'info>,
//     signer_seeds: &[&[&[u8]]],
//     amount: u64,
// ) -> Result<()> {
//     token::transfer(
//         CpiContext::new_with_signer(
//             token_program.clone(),
//             Transfer { from: from.clone(), to: to.clone(), authority: authority.clone() },
//             signer_seeds,
//         ),
//         amount,
//     )
// }

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║  ⚠️ Anvil TODO: helper 'mint_lp_to_user' uses Anchor-only types
// ║  (InterfaceAccount, Interface<TokenInterface>, Box<Account>, etc.) that
// ║  don't exist on Pinocchio. Body commented out below; instruction call sites
// ║  are also commented out so the program compiles. MANUAL PORT REQUIRED.
// ╚════════════════════════════════════════════════════════════════════════════╝
// fn mint_lp_to_user<'info>(
//     token_program: &AccountInfo<'info>,
//     mint: &AccountInfo<'info>,
//     to: &AccountInfo<'info>,
//     authority: &AccountInfo<'info>,
//     signer_seeds: &[&[&[u8]]],
//     amount: u64,
// ) -> Result<()> {
//     token::mint_to(
//         CpiContext::new_with_signer(
//             token_program.clone(),
//             MintTo { mint: mint.clone(), to: to.clone(), authority: authority.clone() },
//             signer_seeds,
//         ),
//         amount,
//     )
// }

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║  ⚠️ Anvil TODO: helper 'burn_lp_from_user' uses Anchor-only types
// ║  (InterfaceAccount, Interface<TokenInterface>, Box<Account>, etc.) that
// ║  don't exist on Pinocchio. Body commented out below; instruction call sites
// ║  are also commented out so the program compiles. MANUAL PORT REQUIRED.
// ╚════════════════════════════════════════════════════════════════════════════╝
// fn burn_lp_from_user<'info>(
//     token_program: &AccountInfo<'info>,
//     mint: &AccountInfo<'info>,
//     from: &AccountInfo<'info>,
//     authority: &AccountInfo<'info>,
//     amount: u64,
// ) -> Result<()> {
//     token::burn(
//         CpiContext::new(
//             token_program.clone(),
//             Burn { mint: mint.clone(), from: from.clone(), authority: authority.clone() },
//         ),
//         amount,
//     )
// }

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum AmmError {
    /// Invalid fee rate
    InvalidFeeRate = 6000,
    /// Invalid price
    InvalidPrice = 6001,
    /// Invalid amount
    InvalidAmount = 6002,
    /// Pool is frozen
    PoolFrozen = 6003,
    /// Slippage exceeded
    SlippageExceeded = 6004,
    /// Insufficient liquidity
    InsufficientLiquidity = 6005,
    /// Unauthorized
    Unauthorized = 6006,
    /// No protocol fees accrued
    NoProtocolFees = 6007,
    /// Arithmetic overflow
    Overflow = 6008,
    /// Arithmetic underflow
    Underflow = 6009,
}

pub use AmmError::*;

impl From<AmmError> for ProgramError {
    fn from(error: AmmError) -> Self {
        ProgramError::Custom(error as u32)
    }
}