//! Counter — generated by Anvil v0.4.0
//! Source framework: Anchor → Target: Native
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]
#![allow(unexpected_cfgs, dead_code, deprecated, unused_imports)]

use borsh::{BorshDeserialize, BorshSerialize};
use solana_program::{
    account_info::AccountInfo,
    entrypoint,
    entrypoint::ProgramResult,
    program::invoke_signed,
    program_error::ProgramError,
    pubkey::Pubkey,
    system_instruction,
    sysvar::Sysvar,
};

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if program_id != &ID {
        return Err(ProgramError::IncorrectProgramId);
    }

    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [11, 18, 104, 9, 104, 174, 59, 33] => increment(program_id, accounts, data),
        [106, 227, 168, 59, 248, 27, 150, 101] => decrement(program_id, accounts, data),
        [23, 81, 251, 84, 138, 183, 240, 214] => reset(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

pub fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 3 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let counter = &accounts[0];
    let authority = &accounts[1];
    let _system_program = &accounts[2];

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !counter.is_writable || !authority.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let start_value: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, bump_counter) = Pubkey::find_program_address(&[b"counter", authority.key.as_ref()], program_id);
    if expected_key != *counter.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_counter_seeds: &[&[u8]] = &[
            b"counter",
            authority.key.as_ref(),
            &[bump_counter],
        ];
    let init_counter_signer_seeds = &[&init_counter_seeds[..]];
    create_program_account(counter, authority, (8 + CounterAccount::INIT_SPACE) as u64, program_id, init_counter_signer_seeds)?;
    {
        let mut __init_data = counter.data.borrow_mut();
        __init_data[..8].copy_from_slice(&CounterAccount::DISCRIMINATOR);
    }
    let counter_account = counter;
    let mut counter = CounterAccount { authority: Pubkey::default(), count: 0, bump: 0 };
    counter.authority = *authority.key;
    counter.count = start_value;
    counter.bump = bump_counter;
    CounterAccount::write(&mut counter_account.data.borrow_mut(), &counter)?;
    Ok(())

}

pub fn increment(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !counter.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if counter.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, _bump_counter) = Pubkey::find_program_address(&[b"counter", authority.key.as_ref()], program_id);
    if expected_key != *counter.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let counter_account = counter;
    let mut counter = CounterAccount::read(&counter_account.data.borrow())?;
    if counter.authority != *authority.key {
        return Err(ProgramError::InvalidAccountData);
    }
    counter.count = counter.count.checked_add(amount).ok_or(CounterError::Overflow)?;
    CounterAccount::write(&mut counter_account.data.borrow_mut(), &counter)?;
    Ok(())

}

pub fn decrement(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !counter.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if counter.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, _bump_counter) = Pubkey::find_program_address(&[b"counter", authority.key.as_ref()], program_id);
    if expected_key != *counter.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let counter_account = counter;
    let mut counter = CounterAccount::read(&counter_account.data.borrow())?;
    if counter.authority != *authority.key {
        return Err(ProgramError::InvalidAccountData);
    }
    counter.count = counter.count.checked_sub(amount).ok_or(CounterError::Underflow)?;
    CounterAccount::write(&mut counter_account.data.borrow_mut(), &counter)?;
    Ok(())

}

pub fn reset(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let counter = &accounts[0];
    let authority = &accounts[1];

    if !authority.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !counter.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if counter.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, _bump_counter) = Pubkey::find_program_address(&[b"counter", authority.key.as_ref()], program_id);
    if expected_key != *counter.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let counter_account = counter;
    let mut counter = CounterAccount::read(&counter_account.data.borrow())?;
    if counter.authority != *authority.key {
        return Err(ProgramError::InvalidAccountData);
    }
    counter.count = 0;
    CounterAccount::write(&mut counter_account.data.borrow_mut(), &counter)?;
    Ok(())

}

#[repr(C)]
pub struct CounterAccount {
    pub authority: Pubkey,
    pub count: u64,
    pub bump: u8,
}

impl CounterAccount {
    pub const DISCRIMINATOR: [u8; 8] = [164, 8, 153, 71, 8, 44, 93, 22];
    pub const INIT_SPACE: usize = 41;
    pub const LEN: usize = 41;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // Alias to dodge field-name shadowing — a field named `data` would
        // shadow the parameter and break subsequent field reads.
        let __data_buf: &[u8] = data;
        let mut offset = 8usize;
        let authority: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let count: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = __data_buf[offset];
        Ok(Self { authority, count, bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let __data_buf: &mut [u8] = data;
        let mut offset = 8usize;
        __data_buf[offset..offset + 32].copy_from_slice(&value.authority.as_ref());
        offset += 32;
        __data_buf[offset..offset + 8].copy_from_slice(&value.count.to_le_bytes());
        offset += 8;
        __data_buf[offset] = value.bump as u8;
        Ok(())
    }

    /// Borsh-style convenience wrapper: borrow the account's data buffer
    /// and write the value into it. Mirrors Pinocchio's save() so the same
    /// emitter call site (`Type::save(account, &value)`) works on both.
    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }

    /// Mirror of Pinocchio's from_account_info — the body emitter calls
    /// `<Type>::from_account_info(account)?` cross-target, so Native
    /// must expose the same signature even though it could equivalently
    /// borrow + read inline. Without this, programs whose handlers don't
    /// directly call `::read(...)` (most non-trivial Anchor sources)
    /// fail Native cargo build with E0599 'no associated item named
    /// from_account_info'.
    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }
}

pub fn create_program_account<'a>(
    account: &AccountInfo<'a>,
    payer: &AccountInfo<'a>,
    space: u64,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let rent = solana_program::sysvar::rent::Rent::get()?;
    let lamports = rent.minimum_balance(space as usize);
    let create_ix = system_instruction::create_account(
        payer.key,
        account.key,
        lamports,
        space,
        program_id,
    );
    invoke_signed(
        &create_ix,
        &[payer.clone(), account.clone()],
        signer_seeds,
    )?;
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum CounterError {
    /// Counter overflow
    Overflow = 6000,
    /// Counter underflow
    Underflow = 6001,
}

pub use CounterError::*;

impl From<CounterError> for ProgramError {
    fn from(error: CounterError) -> Self {
        ProgramError::Custom(error as u32)
    }
}

impl std::fmt::Display for CounterError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl std::error::Error for CounterError {}