//! Escrow — generated by Anvil v0.3.0
//! Source framework: Anchor → Target: Native
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]
#![allow(unexpected_cfgs, dead_code, deprecated, unused_imports)]

use borsh::{BorshDeserialize, BorshSerialize};
use solana_program::{
    account_info::AccountInfo,
    entrypoint,
    entrypoint::ProgramResult,
    program::invoke,
    program::invoke_signed,
    program_error::ProgramError,
    pubkey::Pubkey,
    system_instruction,
    sysvar::Sysvar,
};
use spl_associated_token_account::instruction::create_associated_token_account as spl_create_ata_ix;
use solana_program::sysvar::rent::Rent;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [253, 215, 165, 116, 36, 108, 68, 80] => create_escrow(program_id, accounts, data),
        [193, 2, 224, 245, 36, 116, 65, 154] => accept_escrow(program_id, accounts, data),
        [156, 203, 54, 179, 38, 72, 33, 21] => cancel_escrow(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

pub fn create_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let maker = &accounts[0];
    let mint_a = &accounts[1];
    let mint_b = &accounts[2];
    let maker_ata_a = &accounts[3];
    let escrow = &accounts[4];
    let vault = &accounts[5];
    let _system_program = &accounts[6];
    let _token_program = &accounts[7];
    let _associated_token_program = &accounts[8];

    if !maker.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !maker.is_writable || !maker_ata_a.is_writable || !escrow.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let seed: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let deposit_amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let receive_amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, bump_escrow) = Pubkey::find_program_address(&[b"escrow", maker.key.as_ref(), seed.to_le_bytes().as_ref()], program_id);
    if expected_key != *escrow.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_seed_bytes = seed.to_le_bytes();
    let init_escrow_seeds: &[&[u8]] = &[
            b"escrow",
            maker.key.as_ref(),
            init_seed_bytes.as_ref(),
            &[bump_escrow],
        ];
    let init_escrow_signer_seeds = &[&init_escrow_seeds[..]];
    create_program_account(escrow, maker, (8 + Escrow::INIT_SPACE) as u64, program_id, init_escrow_signer_seeds)?;
    // Init token account: vault
    let __ta_lamports = Rent::get()?.minimum_balance(165);
    let __ta_create = system_instruction::create_account(
        maker.key,
        vault.key,
        __ta_lamports,
        165,
        &spl_token::id(),
    );
    invoke(&__ta_create, &[maker.clone(), vault.clone()])?;
    let __ta_init = spl_token::instruction::initialize_account3(
        &spl_token::id(),
        vault.key,
        mint_a.key,
        escrow.key,
    )?;
    invoke(&__ta_init, &[vault.clone(), mint_a.clone()])?;
    let escrow_account = escrow;
    let mut escrow = Escrow {
        maker: Pubkey::default(),
        mint_a: Pubkey::default(),
        mint_b: Pubkey::default(),
        receive_amount: 0,
        seed: 0,
        bump: 0,
    };
    escrow.maker = *maker.key;
    escrow.mint_a = *mint_a.key;
    escrow.mint_b = *mint_b.key;
    escrow.receive_amount = receive_amount;
    escrow.seed = seed;
    escrow.bump = bump_escrow;
    // SPL Token transfer — maker_ata_a → vault
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        maker_ata_a.key,
        vault.key,
        maker.key,
        &[],
        deposit_amount,
    )?;
    invoke(
        &transfer_ix,
        &[maker_ata_a.clone(), vault.clone(), maker.clone()],
    )?;
    Escrow::write(&mut escrow_account.data.borrow_mut(), &escrow)?;
    Ok(())

}

pub fn accept_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 12 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let taker = &accounts[0];
    let maker = &accounts[1];
    let mint_a = &accounts[2];
    let mint_b = &accounts[3];
    let taker_ata_b = &accounts[4];
    let taker_ata_a = &accounts[5];
    let maker_ata_b = &accounts[6];
    let escrow = &accounts[7];
    let vault = &accounts[8];
    let _system_program = &accounts[9];
    let _token_program = &accounts[10];
    let _associated_token_program = &accounts[11];

    if !taker.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !taker.is_writable || !taker_ata_b.is_writable || !taker_ata_a.is_writable || !maker_ata_b.is_writable || !escrow.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    // Create Associated Token Account: taker_ata_a
    let create_ata_ix = spl_create_ata_ix(
        taker.key,
        taker.key,
        mint_a.key,
        &spl_token::id(),
    );
    invoke(
        &create_ata_ix,
        &[taker.clone(), taker_ata_a.clone(), taker.clone(), mint_a.clone()],
    )?;
    // Create Associated Token Account: maker_ata_b
    let create_ata_ix = spl_create_ata_ix(
        taker.key,
        maker.key,
        mint_b.key,
        &spl_token::id(),
    );
    invoke(
        &create_ata_ix,
        &[taker.clone(), maker_ata_b.clone(), maker.clone(), mint_b.clone()],
    )?;
    let escrow_account = escrow;
    let escrow = Escrow::read(&escrow_account.data.borrow())?;
    if escrow.maker != *maker.key {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.mint_a != *mint_a.key {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.mint_b != *mint_b.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let (expected_key, _bump_escrow) = Pubkey::find_program_address(&[b"escrow", maker.key.as_ref(), escrow.seed.to_le_bytes().as_ref()], program_id);
    if expected_key != *escrow_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    // PDA signer seeds for 'escrow'
    let seeds = &[
            b"escrow",
            escrow.maker.as_ref(),
            &escrow.seed.to_le_bytes(),
            &[escrow.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer — taker_ata_b → maker_ata_b
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        taker_ata_b.key,
        maker_ata_b.key,
        taker.key,
        &[],
        escrow.receive_amount,
    )?;
    invoke(
        &transfer_ix,
        &[taker_ata_b.clone(), maker_ata_b.clone(), taker.clone()],
    )?;
    // SPL Token transfer (PDA signed) — vault → taker_ata_a
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        vault.key,
        taker_ata_a.key,
        escrow_account.key,
        &[],
        token_account_amount(vault)?,
    )?;
    invoke_signed(
        &transfer_ix,
        &[vault.clone(), taker_ata_a.clone(), escrow_account.clone()],
        signer_seeds,
    )?;
    // SPL Token close account — vault
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        vault.key,
        maker.key,
        escrow_account.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[vault.clone(), maker.clone(), escrow_account.clone()],
        signer_seeds,
    )?;
    // SPL Token close account — vault
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        vault.key,
        maker.key,
        escrow_account.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[vault.clone(), maker.clone(), escrow_account.clone()],
        signer_seeds,
    )?;
    close_program_account(escrow_account, maker)?;
    Ok(())

}

pub fn cancel_escrow(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 6 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let maker = &accounts[0];
    let mint_a = &accounts[1];
    let maker_ata_a = &accounts[2];
    let escrow = &accounts[3];
    let vault = &accounts[4];
    let _token_program = &accounts[5];

    if !maker.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !maker.is_writable || !maker_ata_a.is_writable || !escrow.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let escrow_account = escrow;
    let escrow = Escrow::read(&escrow_account.data.borrow())?;
    if escrow.maker != *maker.key {
        return Err(ProgramError::InvalidAccountData);
    }
    if escrow.mint_a != *mint_a.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let (expected_key, _bump_escrow) = Pubkey::find_program_address(&[b"escrow", maker.key.as_ref(), escrow.seed.to_le_bytes().as_ref()], program_id);
    if expected_key != *escrow_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    // PDA signer seeds for 'escrow'
    let seeds = &[
            b"escrow",
            escrow.maker.as_ref(),
            &escrow.seed.to_le_bytes(),
            &[escrow.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → maker_ata_a
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        vault.key,
        maker_ata_a.key,
        escrow_account.key,
        &[],
        token_account_amount(vault)?,
    )?;
    invoke_signed(
        &transfer_ix,
        &[vault.clone(), maker_ata_a.clone(), escrow_account.clone()],
        signer_seeds,
    )?;
    // SPL Token close account — vault
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        vault.key,
        maker.key,
        escrow_account.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[vault.clone(), maker.clone(), escrow_account.clone()],
        signer_seeds,
    )?;
    // SPL Token close account — vault
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        vault.key,
        maker.key,
        escrow_account.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[vault.clone(), maker.clone(), escrow_account.clone()],
        signer_seeds,
    )?;
    close_program_account(escrow_account, maker)?;
    Ok(())

}

#[repr(C)]
pub struct Escrow {
    pub maker: Pubkey,
    pub mint_a: Pubkey,
    pub mint_b: Pubkey,
    pub receive_amount: u64,
    pub seed: u64,
    pub bump: u8,
}

impl Escrow {
    pub const DISCRIMINATOR: [u8; 8] = [31, 213, 123, 187, 186, 22, 218, 155];
    pub const INIT_SPACE: usize = 113;
    pub const LEN: usize = 113;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let maker: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let mint_a: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let mint_b: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let receive_amount: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let seed: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = data[offset];
        Ok(Self { maker, mint_a, mint_b, receive_amount, seed, bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.maker.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint_a.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint_b.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.receive_amount.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.seed.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        Ok(())
    }

    /// Borsh-style convenience wrapper: borrow the account's data buffer
    /// and write the value into it. Mirrors Pinocchio's save() so the same
    /// emitter call site (`Type::save(account, &value)`) works on both.
    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }

    /// Mirror of Pinocchio's from_account_info — the body emitter calls
    /// `<Type>::from_account_info(account)?` cross-target, so Native
    /// must expose the same signature even though it could equivalently
    /// borrow + read inline. Without this, programs whose handlers don't
    /// directly call `::read(...)` (most non-trivial Anchor sources)
    /// fail Native cargo build with E0599 'no associated item named
    /// from_account_info'.
    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }
}

pub fn create_program_account<'a>(
    account: &AccountInfo<'a>,
    payer: &AccountInfo<'a>,
    space: u64,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let rent = solana_program::sysvar::rent::Rent::get()?;
    let lamports = rent.minimum_balance(space as usize);
    let create_ix = system_instruction::create_account(
        payer.key,
        account.key,
        lamports,
        space,
        program_id,
    );
    invoke_signed(
        &create_ix,
        &[payer.clone(), account.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn spl_token_transfer<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
) -> ProgramResult {
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke(
        &transfer_ix,
        &[from.clone(), to.clone(), authority.clone()],
    )?;
    Ok(())
}

pub fn spl_token_transfer_signed<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke_signed(
        &transfer_ix,
        &[from.clone(), to.clone(), authority.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn spl_token_close_account_signed<'a>(
    account: &AccountInfo<'a>,
    destination: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        account.key,
        destination.key,
        authority.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[account.clone(), destination.clone(), authority.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn close_program_account<'a>(
    account: &AccountInfo<'a>,
    destination: &AccountInfo<'a>,
) -> ProgramResult {
    if account.key == destination.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    **destination.try_borrow_mut_lamports()? = destination
        .lamports()
        .checked_add(lamports)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    **account.try_borrow_mut_lamports()? = 0;
    account.data.borrow_mut().fill(0);
    Ok(())
}

/// Read the amount field from an SPL Token Account (offset 64, 8 bytes LE u64)
pub fn token_account_amount<'a>(account: &AccountInfo<'a>) -> Result<u64, ProgramError> {
    let data = account.data.borrow();
    if data.len() < 72 {
        return Err(ProgramError::InvalidAccountData);
    }
    Ok(u64::from_le_bytes(
        data[64..72]
            .try_into()
            .map_err(|_| ProgramError::InvalidAccountData)?
    ))
}