//! Marketplace — generated by Anvil v0.3.0
//! Source framework: Anchor → Target: Native
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]
#![allow(unexpected_cfgs, dead_code, deprecated, unused_imports)]

use borsh::{BorshDeserialize, BorshSerialize};
use solana_program::{
    account_info::AccountInfo,
    entrypoint,
    entrypoint::ProgramResult,
    program::invoke,
    program::invoke_signed,
    program_error::ProgramError,
    pubkey::Pubkey,
    system_instruction,
    sysvar::Sysvar,
};
use spl_associated_token_account::instruction::create_associated_token_account as spl_create_ata_ix;
use solana_program::sysvar::rent::Rent;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [54, 174, 193, 67, 17, 41, 132, 38] => list(program_id, accounts, data),
        [55, 136, 205, 107, 107, 173, 4, 31] => delist(program_id, accounts, data),
        [21, 93, 113, 154, 193, 160, 242, 168] => purchase(program_id, accounts, data),
        [232, 253, 195, 247, 148, 212, 73, 222] => update_fee(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

pub fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let marketplace = &accounts[0];
    let admin = &accounts[1];
    let treasury = &accounts[2];
    let _system_program = &accounts[3];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !marketplace.is_writable || !admin.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 2 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(2);
    remaining = rest;
    let fee_bps: u16 = u16::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, bump_marketplace) = Pubkey::find_program_address(&[b"marketplace"], program_id);
    if expected_key != *marketplace.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_marketplace_seeds: &[&[u8]] = &[
            b"marketplace",
            &[bump_marketplace],
        ];
    let init_marketplace_signer_seeds = &[&init_marketplace_seeds[..]];
    create_program_account(marketplace, admin, (8 + Marketplace::LEN) as u64, program_id, init_marketplace_signer_seeds)?;
    if !(fee_bps <= 10000) {
        return Err(MarketplaceError::InvalidFeeBps.into());
    }
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace {
        admin: Pubkey::default(),
        fee_bps: 0,
        treasury: Pubkey::default(),
        bump: 0,
        listing_count: 0,
    };
    marketplace.admin = *admin.key;
    marketplace.fee_bps = fee_bps;
    marketplace.treasury = *treasury.key;
    marketplace.bump = bump_marketplace;
    marketplace.listing_count = 0;
    Marketplace::write(&mut marketplace_account.data.borrow_mut(), &marketplace)?;
    Ok(())

}

pub fn list(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let seller = &accounts[0];
    let nft_mint = &accounts[1];
    let seller_ata = &accounts[2];
    let listing = &accounts[3];
    let marketplace = &accounts[4];
    let vault = &accounts[5];
    let _token_program = &accounts[6];
    let _associated_token_program = &accounts[7];
    let _system_program = &accounts[8];

    if !seller.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !seller.is_writable || !seller_ata.is_writable || !listing.is_writable || !marketplace.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if marketplace.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let price: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let seed: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, bump_listing) = Pubkey::find_program_address(&[b"listing", seller.key.as_ref(), &seed.to_le_bytes()], program_id);
    if expected_key != *listing.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_seed_bytes = seed.to_le_bytes();
    let init_listing_seeds: &[&[u8]] = &[
            b"listing",
            seller.key.as_ref(),
            &init_seed_bytes,
            &[bump_listing],
        ];
    let init_listing_signer_seeds = &[&init_listing_seeds[..]];
    create_program_account(listing, seller, (8 + Listing::LEN) as u64, program_id, init_listing_signer_seeds)?;
    // Init token account: vault
    let __ta_lamports = Rent::get()?.minimum_balance(165);
    let __ta_create = system_instruction::create_account(
        seller.key,
        vault.key,
        __ta_lamports,
        165,
        &spl_token::id(),
    );
    invoke(&__ta_create, &[seller.clone(), vault.clone()])?;
    let __ta_init = spl_token::instruction::initialize_account3(
        &spl_token::id(),
        vault.key,
        nft_mint.key,
        listing.key,
    )?;
    invoke(&__ta_init, &[vault.clone(), nft_mint.clone()])?;
    let (expected_key, _bump_marketplace) = Pubkey::find_program_address(&[b"marketplace"], program_id);
    if expected_key != *marketplace.key {
        return Err(ProgramError::InvalidSeeds);
    }
    if !(price > 0) {
        return Err(MarketplaceError::InvalidPrice.into());
    }
    let listing_account = listing;
    let mut listing = Listing {
        seller: Pubkey::default(),
        mint: Pubkey::default(),
        price: 0,
        seed: 0,
        bump: 0,
        marketplace: Pubkey::default(),
        vault: Pubkey::default(),
        is_active: false,
    };
    listing.seller = *seller.key;
    listing.mint = *nft_mint.key;
    listing.price = price;
    listing.seed = seed;
    listing.bump = bump_listing;
    listing.marketplace = *marketplace.key;
    listing.vault = *vault.key;
    listing.is_active = true;
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::read(&marketplace_account.data.borrow())?;
    marketplace.listing_count = marketplace.listing_count.checked_add(1).ok_or(MarketplaceError::Overflow)?;
    // SPL Token transfer — seller_ata → vault
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        seller_ata.key,
        vault.key,
        seller.key,
        &[],
        1,
    )?;
    invoke(
        &transfer_ix,
        &[seller_ata.clone(), vault.clone(), seller.clone()],
    )?;
    Listing::write(&mut listing_account.data.borrow_mut(), &listing)?;
    Marketplace::write(&mut marketplace_account.data.borrow_mut(), &marketplace)?;
    Ok(())

}

pub fn delist(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let seller = &accounts[0];
    let _nft_mint = &accounts[1];
    let seller_ata = &accounts[2];
    let listing = &accounts[3];
    let marketplace = &accounts[4];
    let vault = &accounts[5];
    let _token_program = &accounts[6];
    let _associated_token_program = &accounts[7];
    let _system_program = &accounts[8];

    if !seller.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !seller.is_writable || !seller_ata.is_writable || !listing.is_writable || !marketplace.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if listing.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if marketplace.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let listing_account = listing;
    let listing = Listing::read(&listing_account.data.borrow())?;
    if listing.marketplace != *marketplace.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let (expected_key, _bump_listing) = Pubkey::find_program_address(&[b"listing", seller.key.as_ref(), &listing.seed.to_le_bytes()], program_id);
    if expected_key != *listing_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let (expected_key, _bump_marketplace) = Pubkey::find_program_address(&[b"marketplace"], program_id);
    if expected_key != *marketplace.key {
        return Err(ProgramError::InvalidSeeds);
    }
    if !(*vault.key == listing.vault) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if !listing.is_active {
        return Err(MarketplaceError::ListingNotActive.into());
    }
    if !(listing.seller == *seller.key) {
        return Err(MarketplaceError::Unauthorized.into());
    }
    // PDA signer seeds for 'listing'
    let seeds = &[
            b"listing",
            listing.seller.as_ref(),
            &listing.seed.to_le_bytes(),
            &[listing.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → seller_ata
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        vault.key,
        seller_ata.key,
        listing_account.key,
        &[],
        1,
    )?;
    invoke_signed(
        &transfer_ix,
        &[vault.clone(), seller_ata.clone(), listing_account.clone()],
        signer_seeds,
    )?;
    // SPL Token close account — vault
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        vault.key,
        seller.key,
        listing_account.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[vault.clone(), seller.clone(), listing_account.clone()],
        signer_seeds,
    )?;
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::read(&marketplace_account.data.borrow())?;
    marketplace.listing_count = marketplace.listing_count.checked_sub(1).ok_or(MarketplaceError::Underflow)?;
    close_program_account(listing_account, seller)?;
    Marketplace::write(&mut marketplace_account.data.borrow_mut(), &marketplace)?;
    Ok(())

}

pub fn purchase(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 11 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let buyer = &accounts[0];
    let seller = &accounts[1];
    let nft_mint = &accounts[2];
    let buyer_ata = &accounts[3];
    let listing = &accounts[4];
    let marketplace = &accounts[5];
    let treasury = &accounts[6];
    let vault = &accounts[7];
    let _token_program = &accounts[8];
    let _associated_token_program = &accounts[9];
    let _system_program = &accounts[10];

    if !buyer.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !buyer.is_writable || !seller.is_writable || !buyer_ata.is_writable || !listing.is_writable || !marketplace.is_writable || !treasury.is_writable || !vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if listing.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if marketplace.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    // Create Associated Token Account: buyer_ata
    let create_ata_ix = spl_create_ata_ix(
        buyer.key,
        buyer.key,
        nft_mint.key,
        &spl_token::id(),
    );
    invoke(
        &create_ata_ix,
        &[buyer.clone(), buyer_ata.clone(), buyer.clone(), nft_mint.clone()],
    )?;
    let listing_account = listing;
    let listing = Listing::read(&listing_account.data.borrow())?;
    if listing.marketplace != *marketplace.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let (expected_key, _bump_listing) = Pubkey::find_program_address(&[b"listing", seller.key.as_ref(), &listing.seed.to_le_bytes()], program_id);
    if expected_key != *listing_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let (expected_key, _bump_marketplace) = Pubkey::find_program_address(&[b"marketplace"], program_id);
    if expected_key != *marketplace.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::read(&marketplace_account.data.borrow())?;
    if !(*treasury.key == marketplace.treasury) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if !(*vault.key == listing.vault) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if !listing.is_active {
        return Err(MarketplaceError::ListingNotActive.into());
    }
    let fee = listing.price.checked_mul(marketplace.fee_bps as u64).ok_or(MarketplaceError::Overflow)?
            .checked_div(10000).ok_or(MarketplaceError::Overflow)?;
    let seller_amount = listing.price.checked_sub(fee).ok_or(MarketplaceError::Underflow)?;
    // System transfer
    let transfer_ix = system_instruction::transfer(buyer.key, seller.key, seller_amount);
    invoke(
        &transfer_ix,
        &[buyer.clone(), seller.clone()],
    )?;
    // System transfer
    let transfer_ix = system_instruction::transfer(buyer.key, treasury.key, fee);
    invoke(
        &transfer_ix,
        &[buyer.clone(), treasury.clone()],
    )?;
    // PDA signer seeds for 'listing'
    let seeds = &[
            b"listing",
            listing.seller.as_ref(),
            &listing.seed.to_le_bytes(),
            &[listing.bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → buyer_ata
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        vault.key,
        buyer_ata.key,
        listing_account.key,
        &[],
        1,
    )?;
    invoke_signed(
        &transfer_ix,
        &[vault.clone(), buyer_ata.clone(), listing_account.clone()],
        signer_seeds,
    )?;
    // SPL Token close account — vault
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        vault.key,
        seller.key,
        listing_account.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[vault.clone(), seller.clone(), listing_account.clone()],
        signer_seeds,
    )?;
    marketplace.listing_count = marketplace.listing_count.checked_sub(1).ok_or(MarketplaceError::Underflow)?;
    close_program_account(listing_account, seller)?;
    Marketplace::write(&mut marketplace_account.data.borrow_mut(), &marketplace)?;
    Ok(())

}

pub fn update_fee(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let marketplace = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !marketplace.is_writable || !admin.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if marketplace.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 2 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(2);
    remaining = rest;
    let new_fee_bps: u16 = u16::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, _bump_marketplace) = Pubkey::find_program_address(&[b"marketplace"], program_id);
    if expected_key != *marketplace.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let marketplace_account = marketplace;
    let mut marketplace = Marketplace::read(&marketplace_account.data.borrow())?;
    if !(new_fee_bps <= 10000) {
        return Err(MarketplaceError::InvalidFeeBps.into());
    }
    if !(marketplace.admin == *admin.key) {
        return Err(MarketplaceError::Unauthorized.into());
    }
    marketplace.fee_bps = new_fee_bps;
    Marketplace::write(&mut marketplace_account.data.borrow_mut(), &marketplace)?;
    Ok(())

}

#[repr(C)]
pub struct Marketplace {
    pub admin: Pubkey,
    pub fee_bps: u16,
    pub treasury: Pubkey,
    pub bump: u8,
    pub listing_count: u64,
}

impl Marketplace {
    pub const DISCRIMINATOR: [u8; 8] = [70, 222, 41, 62, 78, 3, 32, 174];
    pub const INIT_SPACE: usize = 75;
    pub const LEN: usize = 75;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let admin: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let fee_bps: u16 = u16::from_le_bytes(
            data[offset..offset + 2].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 2;
        let treasury: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let bump: u8 = data[offset];
        offset += 1;
        let listing_count: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        Ok(Self { admin, fee_bps, treasury, bump, listing_count })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.admin.as_ref());
        offset += 32;
        data[offset..offset + 2].copy_from_slice(&value.fee_bps.to_le_bytes());
        offset += 2;
        data[offset..offset + 32].copy_from_slice(&value.treasury.as_ref());
        offset += 32;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset..offset + 8].copy_from_slice(&value.listing_count.to_le_bytes());
        Ok(())
    }

    /// Borsh-style convenience wrapper: borrow the account's data buffer
    /// and write the value into it. Mirrors Pinocchio's save() so the same
    /// emitter call site (`Type::save(account, &value)`) works on both.
    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }

    /// Mirror of Pinocchio's from_account_info — the body emitter calls
    /// `<Type>::from_account_info(account)?` cross-target, so Native
    /// must expose the same signature even though it could equivalently
    /// borrow + read inline. Without this, programs whose handlers don't
    /// directly call `::read(...)` (most non-trivial Anchor sources)
    /// fail Native cargo build with E0599 'no associated item named
    /// from_account_info'.
    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }
}

#[repr(C)]
pub struct Listing {
    pub seller: Pubkey,
    pub mint: Pubkey,
    pub price: u64,
    pub seed: u64,
    pub bump: u8,
    pub marketplace: Pubkey,
    pub vault: Pubkey,
    pub is_active: bool,
}

impl Listing {
    pub const DISCRIMINATOR: [u8; 8] = [218, 32, 50, 73, 43, 134, 26, 58];
    pub const INIT_SPACE: usize = 146;
    pub const LEN: usize = 146;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let seller: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let mint: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let price: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let seed: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let marketplace: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let vault: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let is_active: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        Ok(Self { seller, mint, price, seed, bump, marketplace, vault, is_active })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.seller.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint.as_ref());
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.price.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.seed.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset..offset + 32].copy_from_slice(&value.marketplace.as_ref());
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.vault.as_ref());
        offset += 32;
        data[offset] = if value.is_active { 1 } else { 0 };
        Ok(())
    }

    /// Borsh-style convenience wrapper: borrow the account's data buffer
    /// and write the value into it. Mirrors Pinocchio's save() so the same
    /// emitter call site (`Type::save(account, &value)`) works on both.
    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }

    /// Mirror of Pinocchio's from_account_info — the body emitter calls
    /// `<Type>::from_account_info(account)?` cross-target, so Native
    /// must expose the same signature even though it could equivalently
    /// borrow + read inline. Without this, programs whose handlers don't
    /// directly call `::read(...)` (most non-trivial Anchor sources)
    /// fail Native cargo build with E0599 'no associated item named
    /// from_account_info'.
    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }
}

pub fn create_program_account<'a>(
    account: &AccountInfo<'a>,
    payer: &AccountInfo<'a>,
    space: u64,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let rent = solana_program::sysvar::rent::Rent::get()?;
    let lamports = rent.minimum_balance(space as usize);
    let create_ix = system_instruction::create_account(
        payer.key,
        account.key,
        lamports,
        space,
        program_id,
    );
    invoke_signed(
        &create_ix,
        &[payer.clone(), account.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn transfer_lamports<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    amount: u64,
) -> ProgramResult {
    let transfer_ix = system_instruction::transfer(from.key, to.key, amount);
    invoke(
        &transfer_ix,
        &[from.clone(), to.clone()],
    )?;
    Ok(())
}

pub fn spl_token_transfer<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
) -> ProgramResult {
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke(
        &transfer_ix,
        &[from.clone(), to.clone(), authority.clone()],
    )?;
    Ok(())
}

pub fn spl_token_transfer_signed<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke_signed(
        &transfer_ix,
        &[from.clone(), to.clone(), authority.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn spl_token_close_account_signed<'a>(
    account: &AccountInfo<'a>,
    destination: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let close_ix = spl_token::instruction::close_account(
        &spl_token::id(),
        account.key,
        destination.key,
        authority.key,
        &[],
    )?;
    invoke_signed(
        &close_ix,
        &[account.clone(), destination.clone(), authority.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn close_program_account<'a>(
    account: &AccountInfo<'a>,
    destination: &AccountInfo<'a>,
) -> ProgramResult {
    if account.key == destination.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    **destination.try_borrow_mut_lamports()? = destination
        .lamports()
        .checked_add(lamports)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    **account.try_borrow_mut_lamports()? = 0;
    account.data.borrow_mut().fill(0);
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum MarketplaceError {
    /// Price must be greater than zero
    InvalidPrice = 6000,
    /// Fee must be between 0 and 10000 bps
    InvalidFeeBps = 6001,
    /// Listing is not active
    ListingNotActive = 6002,
    /// Unauthorized
    Unauthorized = 6003,
    /// Arithmetic overflow
    Overflow = 6004,
    /// Arithmetic underflow
    Underflow = 6005,
    /// Invalid vault account
    InvalidVault = 6006,
}

impl From<MarketplaceError> for ProgramError {
    fn from(error: MarketplaceError) -> Self {
        ProgramError::Custom(error as u32)
    }
}

impl std::fmt::Display for MarketplaceError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl std::error::Error for MarketplaceError {}