//! Staking — generated by Anvil v0.3.0
//! Source framework: Anchor → Target: Native
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]
#![allow(unexpected_cfgs, dead_code, deprecated, unused_imports)]

use borsh::{BorshDeserialize, BorshSerialize};
use solana_program::{
    account_info::AccountInfo,
    entrypoint,
    entrypoint::ProgramResult,
    msg,
    program::invoke,
    program::invoke_signed,
    program_error::ProgramError,
    pubkey::Pubkey,
    system_instruction,
    sysvar::Sysvar,
};
use solana_program::sysvar::clock::Clock;
use solana_program::sysvar::rent::Rent;

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub struct StakeEvent {
    pub user: Pubkey,
    pub amount: u64,
    pub timestamp: i64,
}

impl StakeEvent {
    pub const DISCRIMINATOR: [u8; 8] = [226, 134, 188, 173, 19, 33, 75, 175];
}

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub struct RewardEvent {
    pub user: Pubkey,
    pub rewards: u64,
    pub timestamp: i64,
}

impl RewardEvent {
    pub const DISCRIMINATOR: [u8; 8] = [9, 66, 81, 127, 29, 14, 62, 86];
}

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub struct UnstakeEvent {
    pub user: Pubkey,
    pub amount: u64,
    pub rewards: u64,
    pub timestamp: i64,
}

impl UnstakeEvent {
    pub const DISCRIMINATOR: [u8; 8] = [162, 104, 137, 228, 81, 3, 79, 197];
}

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [95, 180, 10, 172, 84, 174, 232, 40] => initialize_pool(program_id, accounts, data),
        [206, 176, 202, 18, 200, 209, 179, 108] => stake(program_id, accounts, data),
        [4, 144, 132, 71, 116, 23, 151, 80] => claim_rewards(program_id, accounts, data),
        [90, 95, 107, 42, 205, 124, 50, 225] => unstake(program_id, accounts, data),
        [160, 15, 12, 189, 160, 0, 243, 245] => pause_pool(program_id, accounts, data),
        [52, 182, 28, 44, 146, 165, 190, 119] => resume_pool(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

pub fn initialize_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let stake_vault = &accounts[1];
    let reward_vault = &accounts[2];
    let stake_mint = &accounts[3];
    let reward_mint = &accounts[4];
    let admin = &accounts[5];
    let token_program = &accounts[6];
    let _system_program = &accounts[7];
    let _rent = &accounts[8];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable || !stake_vault.is_writable || !reward_vault.is_writable || !admin.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if *token_program.key != Pubkey::new_from_array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169]) {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let reward_rate: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let lock_duration: i64 = i64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let max_stake: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, bump_pool) = Pubkey::find_program_address(&[b"pool", stake_mint.key.as_ref()], program_id);
    if expected_key != *pool.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_pool_seeds: &[&[u8]] = &[
            b"pool",
            stake_mint.key.as_ref(),
            &[bump_pool],
        ];
    let init_pool_signer_seeds = &[&init_pool_seeds[..]];
    create_program_account(pool, admin, (8 + StakingPool::INIT_SPACE) as u64, program_id, init_pool_signer_seeds)?;
    {
        let mut __init_data = pool.data.borrow_mut();
        __init_data[..8].copy_from_slice(&StakingPool::DISCRIMINATOR);
    }
    let (expected_key, bump_stake_vault) = Pubkey::find_program_address(&[b"stake_vault", pool.key.as_ref()], program_id);
    if expected_key != *stake_vault.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_stake_vault_seeds: &[&[u8]] = &[
            b"stake_vault",
            pool.key.as_ref(),
            &[bump_stake_vault],
        ];
    let init_stake_vault_signer_seeds = &[&init_stake_vault_seeds[..]];
    // Init token account: stake_vault
    let __ta_lamports = Rent::get()?.minimum_balance(165);
    let __ta_create = system_instruction::create_account(
        admin.key,
        stake_vault.key,
        __ta_lamports,
        165,
        token_program.key,
    );
    invoke_signed(&__ta_create, &[admin.clone(), stake_vault.clone()], init_stake_vault_signer_seeds)?;
    let __ta_init = spl_token::instruction::initialize_account3(
        token_program.key,
        stake_vault.key,
        stake_mint.key,
        pool.key,
    )?;
    invoke(&__ta_init, &[stake_vault.clone(), stake_mint.clone()])?;
    let (expected_key, bump_reward_vault) = Pubkey::find_program_address(&[b"reward_vault", pool.key.as_ref()], program_id);
    if expected_key != *reward_vault.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_reward_vault_seeds: &[&[u8]] = &[
            b"reward_vault",
            pool.key.as_ref(),
            &[bump_reward_vault],
        ];
    let init_reward_vault_signer_seeds = &[&init_reward_vault_seeds[..]];
    // Init token account: reward_vault
    let __ta_lamports = Rent::get()?.minimum_balance(165);
    let __ta_create = system_instruction::create_account(
        admin.key,
        reward_vault.key,
        __ta_lamports,
        165,
        token_program.key,
    );
    invoke_signed(&__ta_create, &[admin.clone(), reward_vault.clone()], init_reward_vault_signer_seeds)?;
    let __ta_init = spl_token::instruction::initialize_account3(
        token_program.key,
        reward_vault.key,
        reward_mint.key,
        pool.key,
    )?;
    invoke(&__ta_init, &[reward_vault.clone(), reward_mint.clone()])?;
    if !(reward_rate > 0) {
        return Err(StakingError::InvalidRewardRate.into());
    }
    if !(lock_duration > 0) {
        return Err(StakingError::InvalidLockDuration.into());
    }
    if !(max_stake > 0) {
        return Err(StakingError::InvalidMaxStake.into());
    }
    let pool_account = pool;
    let mut pool = StakingPool { admin: Pubkey::default(), stake_mint: Pubkey::default(), reward_mint: Pubkey::default(), reward_rate: 0, lock_duration: 0, max_stake: 0, total_staked: 0, bump: 0, stake_vault_bump: 0, reward_vault_bump: 0, is_paused: false };
    pool.admin = *admin.key;
    pool.stake_mint = *stake_mint.key;
    pool.reward_mint = *reward_mint.key;
    pool.reward_rate = reward_rate;
    pool.lock_duration = lock_duration;
    pool.max_stake = max_stake;
    pool.total_staked = 0;
    pool.bump = bump_pool;
    pool.stake_vault_bump = bump_stake_vault;
    pool.reward_vault_bump = bump_reward_vault;
    pool.is_paused = false;
    StakingPool::write(&mut pool_account.data.borrow_mut(), &pool)?;
    Ok(())

}

pub fn stake(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 7 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let user = &accounts[0];
    let user_stake = &accounts[1];
    let pool = &accounts[2];
    let user_stake_ata = &accounts[3];
    let stake_vault = &accounts[4];
    let token_program = &accounts[5];
    let _system_program = &accounts[6];

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !user.is_writable || !user_stake.is_writable || !pool.is_writable || !user_stake_ata.is_writable || !stake_vault.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if *token_program.key != Pubkey::new_from_array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169]) {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining: &[u8] = __ix_data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, bump_user_stake) = Pubkey::find_program_address(&[b"user_stake", user.key.as_ref(), pool.key.as_ref()], program_id);
    if expected_key != *user_stake.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let init_user_stake_seeds: &[&[u8]] = &[
            b"user_stake",
            user.key.as_ref(),
            pool.key.as_ref(),
            &[bump_user_stake],
        ];
    let init_user_stake_signer_seeds = &[&init_user_stake_seeds[..]];
    create_program_account(user_stake, user, (8 + UserStake::INIT_SPACE) as u64, program_id, init_user_stake_signer_seeds)?;
    {
        let mut __init_data = user_stake.data.borrow_mut();
        __init_data[..8].copy_from_slice(&UserStake::DISCRIMINATOR);
    }
    let pool_account = pool;
    let mut pool = StakingPool::read(&pool_account.data.borrow())?;
    let (expected_key, _bump_pool) = Pubkey::find_program_address(&[b"pool", pool.stake_mint.as_ref()], program_id);
    if expected_key != *pool_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let (expected_key, _bump_stake_vault) = Pubkey::find_program_address(&[b"stake_vault", pool_account.key.as_ref()], program_id);
    if expected_key != *stake_vault.key {
        return Err(ProgramError::InvalidSeeds);
    }
    if pool.is_paused {
        return Err(StakingError::PoolPaused.into());
    }
    if !(amount > 0) {
        return Err(StakingError::InvalidAmount.into());
    }
    if !(pool.total_staked.checked_add(amount).ok_or(StakingError::Overflow)? <= pool.max_stake) {
        return Err(StakingError::MaxStakeExceeded.into());
    }
    let clock = solana_program::sysvar::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let user_stake_account = user_stake;
    let mut user_stake = UserStake { owner: Pubkey::default(), pool: Pubkey::default(), amount: 0, staked_at: 0, last_claim: 0, reward_rate_snapshot: 0, bump: 0 };
    user_stake.owner = *user.key;
    user_stake.pool = *pool_account.key;
    user_stake.amount = amount;
    user_stake.staked_at = now;
    user_stake.last_claim = now;
    user_stake.reward_rate_snapshot = pool.reward_rate;
    user_stake.bump = bump_user_stake;
    pool.total_staked = pool.total_staked.checked_add(amount).ok_or(StakingError::Overflow)?;
    // SPL Token transfer — user_stake_ata → stake_vault
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        user_stake_ata.key,
        stake_vault.key,
        user.key,
        &[],
        amount,
    )?;
    invoke(
        &transfer_ix,
        &[user_stake_ata.clone(), stake_vault.clone(), user.clone()],
    )?;
    {
        let __evt = StakeEvent { user: *user.key,
            amount,
            timestamp: now, };
        let __evt_bytes = ::borsh::to_vec(&__evt).map_err(|_| ProgramError::InvalidAccountData)?;
        let mut __evt_payload = StakeEvent::DISCRIMINATOR.to_vec();
        __evt_payload.extend_from_slice(&__evt_bytes);
        solana_program::log::sol_log_data(&[&__evt_payload]);
    }
    UserStake::write(&mut user_stake_account.data.borrow_mut(), &user_stake)?;
    StakingPool::write(&mut pool_account.data.borrow_mut(), &pool)?;
    Ok(())

}

pub fn claim_rewards(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 6 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let user = &accounts[0];
    let user_stake = &accounts[1];
    let pool = &accounts[2];
    let reward_mint = &accounts[3];
    let user_reward_ata = &accounts[4];
    let token_program = &accounts[5];

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !user_stake.is_writable || !reward_mint.is_writable || !user_reward_ata.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if user_stake.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if pool.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if *token_program.key != Pubkey::new_from_array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169]) {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, _bump_user_stake) = Pubkey::find_program_address(&[b"user_stake", user.key.as_ref(), pool.key.as_ref()], program_id);
    if expected_key != *user_stake.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let pool_account = pool;
    let pool = StakingPool::read(&pool_account.data.borrow())?;
    let (expected_key, _bump_pool) = Pubkey::find_program_address(&[b"pool", pool.stake_mint.as_ref()], program_id);
    if expected_key != *pool_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let user_stake_account = user_stake;
    let mut user_stake = UserStake::read(&user_stake_account.data.borrow())?;
    if !(user_stake.owner == *user.key) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if !(*reward_mint.key == pool.reward_mint) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if pool.is_paused {
        return Err(StakingError::PoolPaused.into());
    }
    let clock = solana_program::sysvar::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let elapsed = now.checked_sub(user_stake.last_claim).ok_or(StakingError::Underflow)? as u64;
    let rewards: u64 = (user_stake.amount as u128).checked_mul(elapsed as u128).ok_or(StakingError::Overflow)?
            .checked_mul(user_stake.reward_rate_snapshot as u128).ok_or(StakingError::Overflow)?
            .checked_div(1_000_000).ok_or(StakingError::Overflow)?
            .try_into().map_err(|_| ProgramError::from(StakingError::Overflow))?;
    if !(rewards > 0) {
        return Err(StakingError::NoRewards.into());
    }
    // PDA signer seeds for 'pool'
    let seeds: &[&[u8]] = &[
        b"pool",
        pool.stake_mint.as_ref(),
        &[pool.bump],
    ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token mint_to — reward_mint → user_reward_ata
    let mint_ix = spl_token::instruction::mint_to(
        &spl_token::id(),
        reward_mint.key,
        user_reward_ata.key,
        pool_account.key,
        &[],
        rewards,
    )?;
    invoke_signed(
        &mint_ix,
        &[reward_mint.clone(), user_reward_ata.clone(), pool_account.clone()],
        signer_seeds,
    )?;
    user_stake.last_claim = now;
    {
        let __evt = RewardEvent { user: *user.key,
            rewards,
            timestamp: now, };
        let __evt_bytes = ::borsh::to_vec(&__evt).map_err(|_| ProgramError::InvalidAccountData)?;
        let mut __evt_payload = RewardEvent::DISCRIMINATOR.to_vec();
        __evt_payload.extend_from_slice(&__evt_bytes);
        solana_program::log::sol_log_data(&[&__evt_payload]);
    }
    UserStake::write(&mut user_stake_account.data.borrow_mut(), &user_stake)?;
    Ok(())

}

pub fn unstake(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 9 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let user = &accounts[0];
    let user_stake = &accounts[1];
    let pool = &accounts[2];
    let reward_mint = &accounts[3];
    let user_stake_ata = &accounts[4];
    let stake_vault = &accounts[5];
    let user_reward_ata = &accounts[6];
    let token_program = &accounts[7];
    let _system_program = &accounts[8];

    if !user.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !user.is_writable || !user_stake.is_writable || !pool.is_writable || !reward_mint.is_writable || !user_stake_ata.is_writable || !stake_vault.is_writable || !user_reward_ata.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if user_stake.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if pool.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }
    if *token_program.key != Pubkey::new_from_array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169]) {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (expected_key, _bump_user_stake) = Pubkey::find_program_address(&[b"user_stake", user.key.as_ref(), pool.key.as_ref()], program_id);
    if expected_key != *user_stake.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let pool_account = pool;
    let mut pool = StakingPool::read(&pool_account.data.borrow())?;
    let (expected_key, _bump_pool) = Pubkey::find_program_address(&[b"pool", pool.stake_mint.as_ref()], program_id);
    if expected_key != *pool_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let (expected_key, _bump_stake_vault) = Pubkey::find_program_address(&[b"stake_vault", pool_account.key.as_ref()], program_id);
    if expected_key != *stake_vault.key {
        return Err(ProgramError::InvalidSeeds);
    }
    let user_stake_account = user_stake;
    let user_stake = UserStake::read(&user_stake_account.data.borrow())?;
    if !(user_stake.owner == *user.key) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if !(*reward_mint.key == pool.reward_mint) {
        return Err(ProgramError::InvalidAccountData.into());
    }
    if pool.is_paused {
        return Err(StakingError::PoolPaused.into());
    }
    let clock = solana_program::sysvar::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let unlock_time = user_stake.staked_at.checked_add(pool.lock_duration).ok_or(StakingError::Overflow)?;
    if !(now >= unlock_time) {
        return Err(StakingError::StillLocked.into());
    }
    let elapsed = now.checked_sub(user_stake.last_claim).ok_or(StakingError::Underflow)? as u64;
    let pending_rewards: u64 = (user_stake.amount as u128).checked_mul(elapsed as u128).ok_or(StakingError::Overflow)?
            .checked_mul(user_stake.reward_rate_snapshot as u128).ok_or(StakingError::Overflow)?
            .checked_div(1_000_000).ok_or(StakingError::Overflow)?
            .try_into().map_err(|_| ProgramError::from(StakingError::Overflow))?;
    // PDA signer seeds for 'pool'
    let seeds: &[&[u8]] = &[
        b"pool",
        pool.stake_mint.as_ref(),
        &[pool.bump],
    ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — stake_vault → user_stake_ata
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        stake_vault.key,
        user_stake_ata.key,
        pool_account.key,
        &[],
        user_stake.amount,
    )?;
    invoke_signed(
        &transfer_ix,
        &[stake_vault.clone(), user_stake_ata.clone(), pool_account.clone()],
        signer_seeds,
    )?;
    if pending_rewards > 0 {
            spl_token_mint_to_signed(reward_mint, user_reward_ata, pool_account, pending_rewards, signer_seeds)?;
        }
    pool.total_staked = pool.total_staked.checked_sub(user_stake.amount).ok_or(StakingError::Underflow)?;
    {
        let __evt = UnstakeEvent { user: *user.key,
            amount: user_stake.amount,
            rewards: pending_rewards,
            timestamp: now, };
        let __evt_bytes = ::borsh::to_vec(&__evt).map_err(|_| ProgramError::InvalidAccountData)?;
        let mut __evt_payload = UnstakeEvent::DISCRIMINATOR.to_vec();
        __evt_payload.extend_from_slice(&__evt_bytes);
        solana_program::log::sol_log_data(&[&__evt_payload]);
    }
    close_program_account(user_stake_account, user)?;
    StakingPool::write(&mut pool_account.data.borrow_mut(), &pool)?;
    Ok(())

}

pub fn pause_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = StakingPool::read(&pool_account.data.borrow())?;
    if pool.admin != *admin.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let (expected_key, _bump_pool) = Pubkey::find_program_address(&[b"pool", pool.stake_mint.as_ref()], program_id);
    if expected_key != *pool_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    pool.is_paused = true;
    StakingPool::write(&mut pool_account.data.borrow_mut(), &pool)?;
    Ok(())

}

pub fn resume_pool(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    // Capture instruction data before account bindings; an account named
    // "data" would otherwise shadow the parameter and break arg parsing.
    let __ix_data: &[u8] = data;

    let pool = &accounts[0];
    let admin = &accounts[1];

    if !admin.is_signer {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !pool.is_writable {
        return Err(ProgramError::InvalidAccountData);
    }
    if pool.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !__ix_data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let pool_account = pool;
    let mut pool = StakingPool::read(&pool_account.data.borrow())?;
    if pool.admin != *admin.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let (expected_key, _bump_pool) = Pubkey::find_program_address(&[b"pool", pool.stake_mint.as_ref()], program_id);
    if expected_key != *pool_account.key {
        return Err(ProgramError::InvalidSeeds);
    }
    pool.is_paused = false;
    StakingPool::write(&mut pool_account.data.borrow_mut(), &pool)?;
    Ok(())

}

#[repr(C)]
pub struct StakingPool {
    pub admin: Pubkey,
    pub stake_mint: Pubkey,
    pub reward_mint: Pubkey,
    pub reward_rate: u64,
    pub lock_duration: i64,
    pub max_stake: u64,
    pub total_staked: u64,
    pub bump: u8,
    pub stake_vault_bump: u8,
    pub reward_vault_bump: u8,
    pub is_paused: bool,
}

impl StakingPool {
    pub const DISCRIMINATOR: [u8; 8] = [203, 19, 214, 220, 220, 154, 24, 102];
    pub const INIT_SPACE: usize = 132;
    pub const LEN: usize = 132;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // Alias to dodge field-name shadowing — a field named `data` would
        // shadow the parameter and break subsequent field reads.
        let __data_buf: &[u8] = data;
        let mut offset = 8usize;
        let admin: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let stake_mint: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let reward_mint: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let reward_rate: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let lock_duration: i64 = i64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let max_stake: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let total_staked: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = __data_buf[offset];
        offset += 1;
        let stake_vault_bump: u8 = __data_buf[offset];
        offset += 1;
        let reward_vault_bump: u8 = __data_buf[offset];
        offset += 1;
        let is_paused: bool = match __data_buf[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        Ok(Self { admin, stake_mint, reward_mint, reward_rate, lock_duration, max_stake, total_staked, bump, stake_vault_bump, reward_vault_bump, is_paused })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let __data_buf: &mut [u8] = data;
        let mut offset = 8usize;
        __data_buf[offset..offset + 32].copy_from_slice(&value.admin.as_ref());
        offset += 32;
        __data_buf[offset..offset + 32].copy_from_slice(&value.stake_mint.as_ref());
        offset += 32;
        __data_buf[offset..offset + 32].copy_from_slice(&value.reward_mint.as_ref());
        offset += 32;
        __data_buf[offset..offset + 8].copy_from_slice(&value.reward_rate.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.lock_duration.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.max_stake.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.total_staked.to_le_bytes());
        offset += 8;
        __data_buf[offset] = value.bump as u8;
        offset += 1;
        __data_buf[offset] = value.stake_vault_bump as u8;
        offset += 1;
        __data_buf[offset] = value.reward_vault_bump as u8;
        offset += 1;
        __data_buf[offset] = if value.is_paused { 1 } else { 0 };
        Ok(())
    }

    /// Borsh-style convenience wrapper: borrow the account's data buffer
    /// and write the value into it. Mirrors Pinocchio's save() so the same
    /// emitter call site (`Type::save(account, &value)`) works on both.
    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }

    /// Mirror of Pinocchio's from_account_info — the body emitter calls
    /// `<Type>::from_account_info(account)?` cross-target, so Native
    /// must expose the same signature even though it could equivalently
    /// borrow + read inline. Without this, programs whose handlers don't
    /// directly call `::read(...)` (most non-trivial Anchor sources)
    /// fail Native cargo build with E0599 'no associated item named
    /// from_account_info'.
    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }
}

#[repr(C)]
pub struct UserStake {
    pub owner: Pubkey,
    pub pool: Pubkey,
    pub amount: u64,
    pub staked_at: i64,
    pub last_claim: i64,
    pub reward_rate_snapshot: u64,
    pub bump: u8,
}

impl UserStake {
    pub const DISCRIMINATOR: [u8; 8] = [102, 53, 163, 107, 9, 138, 87, 153];
    pub const INIT_SPACE: usize = 97;
    pub const LEN: usize = 97;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        // Alias to dodge field-name shadowing — a field named `data` would
        // shadow the parameter and break subsequent field reads.
        let __data_buf: &[u8] = data;
        let mut offset = 8usize;
        let owner: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let pool: Pubkey = Pubkey::new_from_array(
            data[offset..offset + 32]
                .try_into()
                .map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 32;
        let amount: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let staked_at: i64 = i64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let last_claim: i64 = i64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let reward_rate_snapshot: u64 = u64::from_le_bytes(
            __data_buf[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = __data_buf[offset];
        Ok(Self { owner, pool, amount, staked_at, last_claim, reward_rate_snapshot, bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let __data_buf: &mut [u8] = data;
        let mut offset = 8usize;
        __data_buf[offset..offset + 32].copy_from_slice(&value.owner.as_ref());
        offset += 32;
        __data_buf[offset..offset + 32].copy_from_slice(&value.pool.as_ref());
        offset += 32;
        __data_buf[offset..offset + 8].copy_from_slice(&value.amount.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.staked_at.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.last_claim.to_le_bytes());
        offset += 8;
        __data_buf[offset..offset + 8].copy_from_slice(&value.reward_rate_snapshot.to_le_bytes());
        offset += 8;
        __data_buf[offset] = value.bump as u8;
        Ok(())
    }

    /// Borsh-style convenience wrapper: borrow the account's data buffer
    /// and write the value into it. Mirrors Pinocchio's save() so the same
    /// emitter call site (`Type::save(account, &value)`) works on both.
    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = account.try_borrow_mut_data()?;
        Self::write(&mut data, value)
    }

    /// Mirror of Pinocchio's from_account_info — the body emitter calls
    /// `<Type>::from_account_info(account)?` cross-target, so Native
    /// must expose the same signature even though it could equivalently
    /// borrow + read inline. Without this, programs whose handlers don't
    /// directly call `::read(...)` (most non-trivial Anchor sources)
    /// fail Native cargo build with E0599 'no associated item named
    /// from_account_info'.
    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = account.try_borrow_data()?;
        Self::read(&data)
    }
}

pub fn create_program_account<'a>(
    account: &AccountInfo<'a>,
    payer: &AccountInfo<'a>,
    space: u64,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let rent = solana_program::sysvar::rent::Rent::get()?;
    let lamports = rent.minimum_balance(space as usize);
    let create_ix = system_instruction::create_account(
        payer.key,
        account.key,
        lamports,
        space,
        program_id,
    );
    invoke_signed(
        &create_ix,
        &[payer.clone(), account.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn spl_token_transfer<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
) -> ProgramResult {
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke(
        &transfer_ix,
        &[from.clone(), to.clone(), authority.clone()],
    )?;
    Ok(())
}

pub fn spl_token_transfer_signed<'a>(
    from: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let transfer_ix = spl_token::instruction::transfer(
        &spl_token::id(),
        from.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke_signed(
        &transfer_ix,
        &[from.clone(), to.clone(), authority.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn spl_token_mint_to_signed<'a>(
    mint: &AccountInfo<'a>,
    to: &AccountInfo<'a>,
    authority: &AccountInfo<'a>,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let mint_ix = spl_token::instruction::mint_to(
        &spl_token::id(),
        mint.key,
        to.key,
        authority.key,
        &[],
        amount,
    )?;
    invoke_signed(
        &mint_ix,
        &[mint.clone(), to.clone(), authority.clone()],
        signer_seeds,
    )?;
    Ok(())
}

pub fn close_program_account<'a>(
    account: &AccountInfo<'a>,
    destination: &AccountInfo<'a>,
) -> ProgramResult {
    if account.key == destination.key {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    **destination.try_borrow_mut_lamports()? = destination
        .lamports()
        .checked_add(lamports)
        .ok_or(ProgramError::ArithmeticOverflow)?;
    **account.try_borrow_mut_lamports()? = 0;
    // F5 — mirror Anchor's close: reassign the account to the System Program
    // and shrink its data to zero. Zeroing data in place (the old behavior)
    // left it program-owned at full length, so a closed account could be
    // revived / re-deserialized as its old type. assign + realloc(0) is what
    // anchor_lang::common::close does and what is_closed (owner == System and
    // data_is_empty) checks.
    account.assign(&solana_program::system_program::ID);
    account.realloc(0, false)?;
    Ok(())
}

/// Read the amount field from an SPL Token Account (offset 64, 8 bytes LE u64)
pub fn token_account_amount<'a>(account: &AccountInfo<'a>) -> Result<u64, ProgramError> {
    let data = account.data.borrow();
    if data.len() < 72 {
        return Err(ProgramError::InvalidAccountData);
    }
    Ok(u64::from_le_bytes(
        data[64..72]
            .try_into()
            .map_err(|_| ProgramError::InvalidAccountData)?
    ))
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum StakingError {
    /// Reward rate must be greater than zero
    InvalidRewardRate = 6000,
    /// Lock duration must be greater than zero
    InvalidLockDuration = 6001,
    /// Max stake must be greater than zero
    InvalidMaxStake = 6002,
    /// Amount must be greater than zero
    InvalidAmount = 6003,
    /// Pool is paused
    PoolPaused = 6004,
    /// Max stake exceeded
    MaxStakeExceeded = 6005,
    /// No rewards to claim
    NoRewards = 6006,
    /// Tokens are still locked
    StillLocked = 6007,
    /// Unauthorized
    Unauthorized = 6008,
    /// Reward mint does not match the pool's registered reward mint
    InvalidRewardMint = 6009,
    /// Arithmetic overflow
    Overflow = 6010,
    /// Arithmetic underflow
    Underflow = 6011,
}

pub use StakingError::*;

impl From<StakingError> for ProgramError {
    fn from(error: StakingError) -> Self {
        ProgramError::Custom(error as u32)
    }
}

impl std::fmt::Display for StakingError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl std::error::Error for StakingError {}