//! Vault — generated by Anvil v0.3.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]
#![allow(unexpected_cfgs, dead_code, deprecated, unused_imports)]

use core::convert::TryInto;
use borsh::{BorshDeserialize, BorshSerialize};
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use pinocchio_system::instructions::Transfer as SystemTransfer;
use pinocchio::instruction::{Seed, Signer};
use pinocchio_system::create_account_with_minimum_balance_signed;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [175, 175, 109, 31, 13, 152, 155, 237] => initialize(program_id, accounts, data),
        [242, 35, 198, 137, 82, 225, 242, 182] => deposit(program_id, accounts, data),
        [183, 18, 70, 156, 148, 109, 161, 34] => withdraw(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

pub fn initialize(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let authority = &accounts[2];
    let _system_program = &accounts[3];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !vault_state.is_writable() || !vault.is_writable() || !authority.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let bump_vault_state = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state.key())?;
    let init_vault_state_seeds: &[&[u8]] = &[
            b"vault_state",
            authority.key().as_ref(),
            &[bump_vault_state],
        ];
    let init_vault_state_signer_seeds = &[&init_vault_state_seeds[..]];
    create_program_account(vault_state, authority, (8 + VaultState::INIT_SPACE) as usize, program_id, init_vault_state_signer_seeds)?;
    let bump_vault = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    let vault_state_account = vault_state;
    let mut vault_state = VaultState {
        authority: [0u8; 32],
        total_deposited: 0,
        bump: 0,
        vault_bump: 0,
    };
    vault_state.authority = *authority.key();
    vault_state.total_deposited = 0;
    vault_state.bump = bump_vault_state;
    vault_state.vault_bump = bump_vault;
    VaultState::save(vault_state_account, &vault_state)?;
    Ok(())

}

pub fn deposit(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let authority = &accounts[2];
    let _system_program = &accounts[3];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !vault_state.is_writable() || !vault.is_writable() || !authority.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault_state.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let _bump_vault_state = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state.key())?;
    let _bump_vault = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    if !(amount > 0) {
        return Err(VaultError::InvalidAmount.into());
    }
    let vault_state_account = vault_state;
    let mut vault_state = VaultState::from_account_info(vault_state_account)?;
    if vault_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    transfer_lamports(authority, vault, amount)?;
    vault_state.total_deposited = vault_state.total_deposited.checked_add(amount).ok_or(VaultError::Overflow)?;
    VaultState::save(vault_state_account, &vault_state)?;
    Ok(())

}

pub fn withdraw(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 4 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let vault_state = &accounts[0];
    let vault = &accounts[1];
    let authority = &accounts[2];
    let _system_program = &accounts[3];

    if !authority.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !vault_state.is_writable() || !vault.is_writable() || !authority.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if vault_state.owner() != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let _bump_vault_state = bump_seed(program_id, &[b"vault_state", authority.key().as_ref()], vault_state.key())?;
    let _bump_vault = bump_seed(program_id, &[b"vault", authority.key().as_ref()], vault.key())?;
    if !(amount > 0) {
        return Err(VaultError::InvalidAmount.into());
    }
    let vault_state_account = vault_state;
    let mut vault_state = VaultState::from_account_info(vault_state_account)?;
    if vault_state.authority != *authority.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    if !(vault.lamports() >= amount) {
        return Err(VaultError::InsufficientFunds.into());
    }
    // PDA signer seeds for 'vault'
    let seeds = &[
            b"vault",
            vault_state.authority.as_ref(),
            &[vault_state.vault_bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // System transfer with PDA signer
    transfer_lamports_signed(vault, authority, amount, signer_seeds)?;
    vault_state.total_deposited = vault_state.total_deposited.checked_sub(amount).ok_or(VaultError::Underflow)?;
    VaultState::save(vault_state_account, &vault_state)?;
    Ok(())

}

#[repr(C)]
pub struct VaultState {
    pub authority: [u8; 32],
    pub total_deposited: u64,
    pub bump: u8,
    pub vault_bump: u8,
}

impl VaultState {
    pub const DISCRIMINATOR: [u8; 8] = [228, 196, 82, 165, 98, 210, 235, 152];
    pub const INIT_SPACE: usize = 42;
    pub const LEN: usize = 42;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;
    pub const SIZE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let authority: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let total_deposited: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let vault_bump: u8 = data[offset];
        Ok(Self { authority, total_deposited, bump, vault_bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.authority);
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.total_deposited.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset] = value.vault_bump as u8;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}

pub fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    for bump in (0..=255u8).rev() {
        let mut seeds_with_bump: [&[u8]; 16] = [&[]; 16];
        let len = seeds.len().min(15);
        seeds_with_bump[..len].copy_from_slice(&seeds[..len]);
        let bump_slice = &[bump];
        seeds_with_bump[len] = bump_slice;
        if let Ok(derived) = pinocchio::pubkey::create_program_address(&seeds_with_bump[..len + 1], program_id) {
            if &derived == expected {
                return Ok(bump);
            }
        }
    }
    Err(ProgramError::InvalidSeeds)
}

pub fn transfer_lamports(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    SystemTransfer {
        from,
        to,
        lamports: amount,
    }
    .invoke()
}

pub fn transfer_lamports_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let seed_group = signer_seeds.first().ok_or(ProgramError::InvalidSeeds)?;
    let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
    for (i, seed) in seed_group.iter().enumerate() {
        if i >= seeds.len() { return Err(ProgramError::InvalidSeeds); }
        seeds[i] = Seed::from(*seed);
    }
    let signer = Signer::from(&seeds[..seed_group.len()]);
    SystemTransfer {
        from,
        to,
        lamports: amount,
    }
    .invoke_signed(&[signer])
}

pub fn create_program_account(
    account: &AccountInfo,
    payer: &AccountInfo,
    space: usize,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    if signer_seeds.len() > 1 {
        return Err(ProgramError::InvalidSeeds);
    }

    let signer_storage = signer_seeds.first().map(|seed_group| {
        let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
        for (index, seed) in seed_group.iter().enumerate() {
            if index >= seeds.len() {
                return Err(ProgramError::InvalidSeeds);
            }
            seeds[index] = Seed::from(*seed);
        }
        Ok((seeds, seed_group.len()))
    }).transpose()?;

    let signer_slice = if let Some((ref seeds, len)) = signer_storage {
        let signer = Signer::from(&seeds[..len]);
        create_account_with_minimum_balance_signed(account, space, program_id, payer, None, &[signer])
    } else {
        create_account_with_minimum_balance_signed(account, space, program_id, payer, None, &[])
    };

    signer_slice
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum VaultError {
    /// Amount must be greater than zero
    InvalidAmount = 6000,
    /// Insufficient funds in vault
    InsufficientFunds = 6001,
    /// Arithmetic overflow
    Overflow = 6002,
    /// Arithmetic underflow
    Underflow = 6003,
}

impl From<VaultError> for ProgramError {
    fn from(error: VaultError) -> Self {
        ProgramError::Custom(error as u32)
    }
}