//! TokenVesting — generated by Anvil v0.2.0
//! Source framework: Anchor → Target: Pinocchio
//!
//! This code was automatically generated. Sections marked with
//! "⚠️ Anvil: Review" should be verified before deployment.
#![deny(clippy::all)]

use core::convert::TryInto;
use borsh::{BorshDeserialize, BorshSerialize};
use pinocchio::{
    account_info::AccountInfo,
    entrypoint,
    program_error::ProgramError,
    pubkey::Pubkey,
    ProgramResult,
};
use pinocchio::instruction::{Seed, Signer};
use pinocchio_system::create_account_with_minimum_balance_signed;
use pinocchio_token::instructions::Transfer as TokenTransfer;
use pinocchio::sysvars::clock::Clock;
use pinocchio::sysvars::Sysvar;

pub const VESTING_SEED: &[u8] = b"vesting";

pub const VAULT_SEED: &[u8] = b"vault";

pub const MAX_SCHEDULES: usize = 10;

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    if instruction_data.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }

    let (discriminator, data) = instruction_data.split_at(8);
    router(program_id, accounts, discriminator, data)
}

fn router(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    discriminator: &[u8],
    data: &[u8],
) -> ProgramResult {
    match discriminator {
        [135, 184, 171, 156, 197, 162, 246, 44] => create_vesting(program_id, accounts, data),
        [253, 249, 15, 206, 28, 127, 193, 241] => release(program_id, accounts, data),
        [170, 23, 31, 34, 133, 173, 93, 242] => revoke(program_id, accounts, data),
        [98, 165, 201, 177, 108, 65, 206, 96] => close(program_id, accounts, data),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn create_vesting(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 8 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let grantor = &accounts[0];
    let vesting = &accounts[1];
    let vault = &accounts[2];
    let grantor_token_account = &accounts[3];
    let mint = &accounts[4];
    let token_program = &accounts[5];
    let system_program = &accounts[6];
    let rent = &accounts[7];

    if !grantor.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !grantor.is_writable() || !vesting.is_writable() || !vault.is_writable() || !grantor_token_account.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }

    // Args
    let mut remaining = data;
    if remaining.len() < 32 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(32);
    remaining = rest;
    let beneficiary: [u8; 32] = arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?;
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let total_amount: u64 = u64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let start_ts: i64 = i64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let cliff_ts: i64 = i64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 8 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(8);
    remaining = rest;
    let end_ts: i64 = i64::from_le_bytes(
        arg_bytes.try_into().map_err(|_| ProgramError::InvalidInstructionData)?
    );
    if remaining.len() < 1 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (arg_bytes, rest) = remaining.split_at(1);
    remaining = rest;
    let revocable: bool = match arg_bytes[0] {
        0 => false,
        1 => true,
        _ => return Err(ProgramError::InvalidInstructionData),
    };
    if !remaining.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }

    let bump_vesting = bump_seed(program_id, &[VESTING_SEED, grantor.key().as_ref(), beneficiary.as_ref()], vesting.key())?;
    let init_vesting_seeds: &[&[u8]] = &[
            VESTING_SEED,
            grantor.key().as_ref(),
            beneficiary.as_ref(),
            &[bump_vesting],
        ];
    let init_vesting_signer_seeds = &[&init_vesting_seeds[..]];
    create_program_account(vesting, grantor, (8 + Vesting::LEN) as usize, program_id, init_vesting_signer_seeds)?;


    if !(total_amount > 0) {
        return Err(VestingError::InvalidAmount.into());
    }
    if !(cliff_ts >= start_ts) {
        return Err(VestingError::InvalidSchedule.into());
    }
    if !(end_ts > cliff_ts) {
        return Err(VestingError::InvalidSchedule.into());
    }
    if !(beneficiary != *grantor.key()) {
        return Err(VestingError::SelfVesting.into());
    }
    let clock = pinocchio::sysvars::clock::Clock::get()?;
    if !(start_ts >= clock.unix_timestamp) {
        return Err(VestingError::StartInPast.into());
    }
    let vesting_account = vesting;
    let mut vesting = Vesting {
        grantor: [0u8; 32],
        beneficiary: [0u8; 32],
        mint: [0u8; 32],
        vault: [0u8; 32],
        total_amount: 0,
        released_amount: 0,
        start_ts: 0,
        cliff_ts: 0,
        end_ts: 0,
        revocable: false,
        revoked: false,
        created_at: 0,
        bump: 0,
        vault_bump: 0,
    };
    vesting.grantor = *grantor.key();
    vesting.beneficiary = beneficiary;
    vesting.mint = *mint.key();
    vesting.vault = *vault.key();
    vesting.total_amount = total_amount;
    vesting.released_amount = 0;
    vesting.start_ts = start_ts;
    vesting.cliff_ts = cliff_ts;
    vesting.end_ts = end_ts;
    vesting.revocable = revocable;
    vesting.revoked = false;
    vesting.created_at = clock.unix_timestamp;
    vesting.bump = bump_vesting;
    vesting.vault_bump = bump_vault;
    // SPL Token transfer — grantor_token_account → vault
    spl_token_transfer(grantor_token_account, vault, grantor, total_amount)?;
    // ⚠️ Anvil: formatted msg!() collapsed to static sol_log for Pinocchio
    pinocchio::log::sol_log("Vesting created: {} tokens for {}");
    Vesting::save(vesting_account, &vesting)?;
    Ok(())

}

fn release(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let beneficiary = &accounts[0];
    let vesting = &accounts[1];
    let vault = &accounts[2];
    let beneficiary_token_account = &accounts[3];
    let token_program = &accounts[4];

    if !beneficiary.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !vesting.is_writable() || !vault.is_writable() || !beneficiary_token_account.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if unsafe { vesting.owner() } != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }


    let vesting_account = vesting;
    let mut vesting = Vesting::from_account_info(vesting_account)?;
    if vesting.beneficiary != *beneficiary.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let bump_vesting = bump_seed(program_id, &[VESTING_SEED, vesting.grantor.as_ref(), beneficiary.key().as_ref()], vesting_account.key())?;
    let bump_vault = bump_seed(program_id, &[VAULT_SEED, vesting_account.key().as_ref()], vault.key())?;
    let clock = pinocchio::sysvars::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    if vesting.revoked {
        return Err(VestingError::VestingRevoked.into());
    }
    if !(now >= vesting.cliff_ts) {
        return Err(VestingError::CliffNotReached.into());
    }
    let vested = vested_amount(
            vesting.total_amount,
            vesting.start_ts,
            vesting.cliff_ts,
            vesting.end_ts,
            now,
        );
    let releasable = vested.checked_sub(vesting.released_amount).ok_or(VestingError::ArithmeticOverflow)?;
    if !(releasable > 0) {
        return Err(VestingError::NothingToRelease.into());
    }
    vesting.released_amount = vesting.released_amount.checked_add(releasable).ok_or(VestingError::ArithmeticOverflow)?;
    let vesting_key = *vesting_account.key();
    let vault_bump = vesting.vault_bump;
    // PDA signer seeds for 'vesting_key'
    let seeds = &[
            VAULT_SEED,
            vesting_key.as_ref(),
            &[vault_bump],
        ];
    let signer_seeds = &[&seeds[..]];
    // SPL Token transfer (PDA signed) — vault → beneficiary_token_account
    spl_token_transfer_signed(vault, beneficiary_token_account, vault, releasable, signer_seeds)?;
    // ⚠️ Anvil: formatted msg!() collapsed to static sol_log for Pinocchio
    pinocchio::log::sol_log("Released {} tokens to beneficiary");
    Vesting::save(vesting_account, &vesting)?;
    Ok(())

}

fn revoke(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let grantor = &accounts[0];
    let vesting = &accounts[1];
    let vault = &accounts[2];
    let grantor_token_account = &accounts[3];
    let token_program = &accounts[4];

    if !grantor.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !vesting.is_writable() || !vault.is_writable() || !grantor_token_account.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if unsafe { vesting.owner() } != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }


    let vesting_account = vesting;
    let mut vesting = Vesting::from_account_info(vesting_account)?;
    if vesting.grantor != *grantor.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let bump_vesting = bump_seed(program_id, &[VESTING_SEED, grantor.key().as_ref(), vesting.beneficiary.as_ref()], vesting_account.key())?;
    let bump_vault = bump_seed(program_id, &[VAULT_SEED, vesting_account.key().as_ref()], vault.key())?;
    if !vesting.revocable {
        return Err(VestingError::NotRevocable.into());
    }
    if vesting.revoked {
        return Err(VestingError::VestingRevoked.into());
    }
    let clock = pinocchio::sysvars::clock::Clock::get()?;
    let now = clock.unix_timestamp;
    let vested = vested_amount(
            vesting.total_amount,
            vesting.start_ts,
            vesting.cliff_ts,
            vesting.end_ts,
            now,
        );
    let unvested = vesting.total_amount.checked_sub(vested).ok_or(VestingError::ArithmeticOverflow)?;
    vesting.revoked = true;
    if unvested > 0 {
            let vesting_key = *vesting_account.key();
            let vault_bump = vesting.vault_bump;
            let seeds: &[&[u8]] = &[VAULT_SEED, vesting_key.as_ref(), &[vault_bump]];

            spl_token_transfer_signed(vault, grantor_token_account, vault, unvested, &[seeds])?;
        }
    // ⚠️ Anvil: formatted msg!() collapsed to static sol_log for Pinocchio
    pinocchio::log::sol_log("Vesting revoked. {} unvested tokens returned to grantor.");
    Vesting::save(vesting_account, &vesting)?;
    Ok(())

}

fn close(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    data: &[u8],
) -> ProgramResult {
    if accounts.len() < 5 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }

    let grantor = &accounts[0];
    let vesting = &accounts[1];
    let vault = &accounts[2];
    let grantor_token_account = &accounts[3];
    let token_program = &accounts[4];

    if !grantor.is_signer() {
        return Err(ProgramError::MissingRequiredSignature);
    }
    if !grantor.is_writable() || !vesting.is_writable() || !vault.is_writable() || !grantor_token_account.is_writable() {
        return Err(ProgramError::InvalidAccountData);
    }
    if unsafe { vesting.owner() } != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    if !data.is_empty() {
        return Err(ProgramError::InvalidInstructionData);
    }


    let vesting_account = vesting;
    let vesting = Vesting::from_account_info(vesting_account)?;
    if vesting.grantor != *grantor.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let bump_vesting = bump_seed(program_id, &[VESTING_SEED, grantor.key().as_ref(), vesting.beneficiary.as_ref()], vesting_account.key())?;
    let bump_vault = bump_seed(program_id, &[VAULT_SEED, vesting_account.key().as_ref()], vault.key())?;
    if !(vesting.revoked || vesting.released_amount == vesting.total_amount) {
        return Err(VestingError::NotCloseable.into());
    }
    let vault_balance = token_account_amount(vault)?;
    if vault_balance > 0 {
            let vesting_key = *vesting_account.key();
            let vault_bump = vesting.vault_bump;
            let seeds: &[&[u8]] = &[VAULT_SEED, vesting_key.as_ref(), &[vault_bump]];

            spl_token_transfer_signed(vault, grantor_token_account, vault, vault_balance, &[seeds])?;
        }
    pinocchio::log::sol_log("Vesting account closed.");
    close_program_account(vesting_account, grantor)?;
    Ok(())

}

#[repr(C)]
pub struct Vesting {
    pub grantor: [u8; 32],
    pub beneficiary: [u8; 32],
    pub mint: [u8; 32],
    pub vault: [u8; 32],
    pub total_amount: u64,
    pub released_amount: u64,
    pub start_ts: i64,
    pub cliff_ts: i64,
    pub end_ts: i64,
    pub revocable: bool,
    pub revoked: bool,
    pub created_at: i64,
    pub bump: u8,
    pub vault_bump: u8,
}

impl Vesting {
    pub const DISCRIMINATOR: [u8; 8] = [100, 149, 66, 138, 95, 200, 128, 241];
    pub const INIT_SPACE: usize = 180;
    pub const LEN: usize = 180;
    pub const TOTAL_LEN: usize = 8 + Self::LEN;
    pub const SPACE: usize = Self::TOTAL_LEN;

    pub fn read(data: &[u8]) -> Result<Self, ProgramError> {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        if data[..8] != Self::DISCRIMINATOR {
            return Err(ProgramError::InvalidAccountData);
        }
        let mut offset = 8usize;
        let grantor: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let beneficiary: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let mint: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let vault: [u8; 32] = data[offset..offset + 32].try_into().map_err(|_| ProgramError::InvalidAccountData)?;
        offset += 32;
        let total_amount: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let released_amount: u64 = u64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let start_ts: i64 = i64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let cliff_ts: i64 = i64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let end_ts: i64 = i64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let revocable: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        offset += 1;
        let revoked: bool = match data[offset] {
            0 => false,
            1 => true,
            _ => return Err(ProgramError::InvalidAccountData),
        };
        offset += 1;
        let created_at: i64 = i64::from_le_bytes(
            data[offset..offset + 8].try_into().map_err(|_| ProgramError::InvalidAccountData)?
        );
        offset += 8;
        let bump: u8 = data[offset];
        offset += 1;
        let vault_bump: u8 = data[offset];
        offset += 1;
        Ok(Self { grantor, beneficiary, mint, vault, total_amount, released_amount, start_ts, cliff_ts, end_ts, revocable, revoked, created_at, bump, vault_bump })
    }

    pub fn write(data: &mut [u8], value: &Self) -> ProgramResult {
        if data.len() < Self::TOTAL_LEN {
            return Err(ProgramError::InvalidAccountData);
        }
        data[..8].copy_from_slice(&Self::DISCRIMINATOR);
        let mut offset = 8usize;
        data[offset..offset + 32].copy_from_slice(&value.grantor);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.beneficiary);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.mint);
        offset += 32;
        data[offset..offset + 32].copy_from_slice(&value.vault);
        offset += 32;
        data[offset..offset + 8].copy_from_slice(&value.total_amount.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.released_amount.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.start_ts.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.cliff_ts.to_le_bytes());
        offset += 8;
        data[offset..offset + 8].copy_from_slice(&value.end_ts.to_le_bytes());
        offset += 8;
        data[offset] = if value.revocable { 1 } else { 0 };
        offset += 1;
        data[offset] = if value.revoked { 1 } else { 0 };
        offset += 1;
        data[offset..offset + 8].copy_from_slice(&value.created_at.to_le_bytes());
        offset += 8;
        data[offset] = value.bump as u8;
        offset += 1;
        data[offset] = value.vault_bump as u8;
        offset += 1;
        Ok(())
    }

    pub fn from_account_info(account: &AccountInfo) -> Result<Self, ProgramError> {
        let data = unsafe { account.borrow_data_unchecked() };
        Self::read(&data)
    }

    pub fn save(account: &AccountInfo, value: &Self) -> ProgramResult {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        Self::write(&mut data, value)
    }
}

fn bump_seed(
    program_id: &Pubkey,
    seeds: &[&[u8]],
    expected: &Pubkey,
) -> Result<u8, ProgramError> {
    for bump in (0..=255u8).rev() {
        let mut seeds_with_bump: [&[u8]; 16] = [&[]; 16];
        let len = seeds.len().min(15);
        seeds_with_bump[..len].copy_from_slice(&seeds[..len]);
        let bump_slice = &[bump];
        seeds_with_bump[len] = bump_slice;
        if let Ok(derived) = pinocchio::pubkey::create_program_address(&seeds_with_bump[..len + 1], program_id) {
            if &derived == expected {
                return Ok(bump);
            }
        }
    }
    Err(ProgramError::InvalidSeeds)
}

fn create_program_account(
    account: &AccountInfo,
    payer: &AccountInfo,
    space: usize,
    program_id: &Pubkey,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    if signer_seeds.len() > 1 {
        return Err(ProgramError::InvalidSeeds);
    }

    let signer_storage = signer_seeds.first().map(|seed_group| {
        let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
        for (index, seed) in seed_group.iter().enumerate() {
            if index >= seeds.len() {
                return Err(ProgramError::InvalidSeeds);
            }
            seeds[index] = Seed::from(*seed);
        }
        Ok((seeds, seed_group.len()))
    }).transpose()?;

    let signer_slice = if let Some((ref seeds, len)) = signer_storage {
        let signer = Signer::from(&seeds[..len]);
        create_account_with_minimum_balance_signed(account, space, program_id, payer, None, &[signer])
    } else {
        create_account_with_minimum_balance_signed(account, space, program_id, payer, None, &[])
    };

    signer_slice
}

fn spl_token_transfer(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
) -> ProgramResult {
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke()
}

fn spl_token_transfer_signed(
    from: &AccountInfo,
    to: &AccountInfo,
    authority: &AccountInfo,
    amount: u64,
    signer_seeds: &[&[&[u8]]],
) -> ProgramResult {
    let seed_group = signer_seeds.first().ok_or(ProgramError::InvalidSeeds)?;
    let mut seeds: [Seed<'_>; 8] = core::array::from_fn(|_| Seed::from(&[][..]));
    for (i, seed) in seed_group.iter().enumerate() {
        if i >= seeds.len() { return Err(ProgramError::InvalidSeeds); }
        seeds[i] = Seed::from(*seed);
    }
    let signer = Signer::from(&seeds[..seed_group.len()]);
    TokenTransfer {
        from,
        to,
        authority,
        amount,
    }
    .invoke_signed(&[signer])
}

fn close_program_account(
    account: &AccountInfo,
    destination: &AccountInfo,
) -> ProgramResult {
    if account.key() == destination.key() {
        return Err(ProgramError::InvalidAccountData);
    }
    let lamports = account.lamports();
    {
        let destination_lamports = unsafe { destination.borrow_mut_lamports_unchecked() };
        *destination_lamports = destination_lamports
            .checked_add(lamports)
            .ok_or(ProgramError::ArithmeticOverflow)?;
    }
    {
        let account_lamports = unsafe { account.borrow_mut_lamports_unchecked() };
        *account_lamports = 0;
    }
    {
        let mut data = unsafe { account.borrow_mut_data_unchecked() };
        for byte in data.iter_mut() {
            *byte = 0;
        }
    }
    Ok(())
}

/// Read the amount field from an SPL Token Account (offset 64, 8 bytes LE u64)
fn token_account_amount(account: &AccountInfo) -> Result<u64, ProgramError> {
    let data = unsafe { account.borrow_data_unchecked() };
    if data.len() < 72 {
        return Err(ProgramError::InvalidAccountData);
    }
    Ok(u64::from_le_bytes(
        data[64..72]
            .try_into()
            .map_err(|_| ProgramError::InvalidAccountData)?
    ))
}

// Carried from source (pure Rust — no Anchor APIs detected)
fn vested_amount(
    total: u64,
    start_ts: i64,
    cliff_ts: i64,
    end_ts: i64,
    now: i64,
) -> u64 {
    if now < cliff_ts {
        return 0;
    }
    if now >= end_ts {
        return total;
    }
    let elapsed = (now - start_ts) as u64;
    let duration = (end_ts - start_ts) as u64;
    total
        .checked_mul(elapsed)
        .and_then(|v| v.checked_div(duration))
        .unwrap_or(0)
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u32)]
pub enum VestingError {
    /// Amount must be greater than zero
    InvalidAmount = 6000,
    /// Invalid vesting schedule: cliff must be >= start, end must be > cliff
    InvalidSchedule = 6001,
    /// Cannot vest tokens to yourself
    SelfVesting = 6002,
    /// Start timestamp is in the past
    StartInPast = 6003,
    /// Cliff period has not been reached yet
    CliffNotReached = 6004,
    /// Nothing to release yet
    NothingToRelease = 6005,
    /// This vesting is not revocable
    NotRevocable = 6006,
    /// This vesting has already been revoked
    VestingRevoked = 6007,
    /// Vesting is not closeable yet
    NotCloseable = 6008,
    /// Arithmetic overflow
    ArithmeticOverflow = 6009,
}

impl From<VestingError> for ProgramError {
    fn from(error: VestingError) -> Self {
        ProgramError::Custom(error as u32)
    }
}